### ISSUE TITLE
Is it possible to print the embedded PDF in Edge?

### ISSUE THREAD

**Issue by LawDeveloper** [pipwerks/PDFObject#100]
Hey guys,

is it possible to print the embedded PDF in Microsoft EDGE? 

I still get the Toolbar I want and selected in Firefox but not in Microsoft EDGE. If I use the regular print-function of Microsoft EDGE it will print out everything. However, I just want to print the PDF.

**Comment by pipwerks** [comment]
Sorry, I don't know. That's outside the scope of PDFObject -- PDFObject has no control or influence over printing a PDF.
