### ISSUE TITLE
How can i give file name that i need to get it when i download the pdf?

### ISSUE THREAD

**Issue by mallikarjuna909** [pipwerks/PDFObject#101]
I've URL, that gives the pdf response, when i'm downloading the document i'm getting the name like 'document.pdf'. But i need exact file name when it is downloading.

**Comment by pipwerks** [comment]
This is unrelated to PDFObject. 

PDFObject embeds the PDF in an HTML page, nothing more. Everything else is handled by the browser or PDF reader plugin.
