### ISSUE TITLE
Specific requirement for Internet Explorer 11 only.

### ISSUE THREAD

**Issue by rohanray** [pipwerks/PDFObject#104]
There is a 3rd party service which sends me a PDF file in either binary format or base64 encoded. Is there any possibility to display the PDF embedded in IE 11 using either binary string or base64 encoded.

From SO and other forums, I concluded that IE 11 supports data uri only for images and not PDF (I might be wrong). So the only option left is to display from binary string. I am using it in a Node App but I do not have the option to first save the retrieved file to Node server and use static URL. 

Please let me know if above is achievable in IE 11.

Thanks,
Rohan.

**Comment by pipwerks** [comment]
I recommend you try this with plain HTML markup first. Are you able to get it working without using PDFObject? You can get some sample plain markup here: https://pdfobject.com/generator/

**Comment by rohanray** [comment]
I got this to work using PDF.js. Hence, closing this.
