### ISSUE TITLE
How to modify the upper right corner of the file name

### ISSUE THREAD

**Issue by kleen** [pipwerks/PDFObject#106]
![image](https://cloud.githubusercontent.com/assets/3284413/19877524/e6b29a2e-a01a-11e6-8a6c-0ec67b968f29.png)

rt

**Comment by pipwerks** [comment]
Unrelated to PDFObject. All PDFObject does is embed the PDF -- toolbars and other view-related issues are controlled by the PDF rendering software (browser, or browser plugin).

**Comment by kleen** [comment]
how to modify the upper right display name .

**Comment by pipwerks** [comment]
This is not controlled by PDFObject.

**Comment by kleen** [comment]
o
