### ISSUE TITLE
pdfOBJECT auto adjust width

### ISSUE THREAD

**Issue by FlorianHergo** [pipwerks/PDFObject#107]
Hi,

The last version is perfect, but i don't find the parameter for auto adjust when load the PDF by width.
Like a same action than button "Adjust to the page".

thanks.

**Comment by pipwerks** [comment]
You would use CSS for adjusting width. Set the PDFObject element to 100% width and it will auto-expand to fill the parent element. See more about specifying width on https://pdfobject.com/ under Getting Started.
