### ISSUE TITLE
customizing save as button in the viewer

### ISSUE THREAD

**Issue by mohelal84** [pipwerks/PDFObject#109]
is there any way to add js function when click download or save as file from the embeded pdf viewer?

**Comment by pipwerks** [comment]
The PDF viewer is controlled by the browser, and is not standardized across browsers. The only way to achieve your goal is to use something like PDF.js, which ensures all visitors see the same PDF viewer. I believe PDF.js can be modified to do what you want, but it is outside the scope of PDFObject.
