### ISSUE TITLE
HTML5 Doctype IE9

### ISSUE THREAD

**Issue by jwagner79** [pipwerks/PDFObject#11]
In my testing I've found that using an object to embed the PDF doesn't work for Adobe reader in IE9 (or maybe it's just me: IE9, Adobe Reader 9.5 or X, Windows 7 x64).

Try the following for example:
```
<!doctype html>
<html>
<body style='height: "100%"; width: "100%"'>
<object type='application/pdf' width='500' height='500' data='http://www.irs.gov/pub/irs-pdf/fw4.pdf'></object>
</body>
</html>
```

However, using an iframe works fine for HTML 5 doctype. I'm not sure if you can reliably detect the doctype in javascript with IE, but one option would be to use an iframe rather than object if the browser supports ActiveX. Something like this in the embed method:
```
if (hasReaderActiveX()) 
  targetNode.innerHTML = '<iframe src="' + url + '" width="' + width + '" height="' + height + '"></iframe>';	    
else 
   targetNode.innerHTML = '<object    data="' +url +'" type="application/pdf" width="' +width +'" height="' +height +'"></object>';
```

**Comment by pipwerks** [comment]
I am investigating switching to `<embed>` now that a couple of years have passed and HTML5 is considered safe for production. (HTML5 officially supports `<embed>`, so PDFObject will remain standards-based if the switch is made, which is important to me.)
