### ISSUE TITLE
No Print Button in Safari 10.0.1

### ISSUE THREAD

**Issue by tallglassofmike** [pipwerks/PDFObject#110]
The PDF loads in Safari but there is no support for print. File > Print just shows a blank preview.

![blank-preview](https://cloud.githubusercontent.com/assets/14119206/20184383/5633dd8c-a71d-11e6-9454-09b8090aa16f.jpg)

I am on a Mac, running OS X Yosemite version 10.10.5.

![safari-no-print-button](https://cloud.githubusercontent.com/assets/14119206/20184131/82868228-a71c-11e6-9378-860389583cfb.jpg)

**Comment by pipwerks** [comment]
Sorry, but this is completely unrelated to PDFObject -- all PDFObject does is embed the PDF into an HTML file using an `<embed>` tag. PDF viewer functionality is controlled by the browser. Or PDF.js if you choose to force the browser to use PDF.js instead.

**Comment by tallglassofmike** [comment]
Oops. Thanks for the clarity.
