### ISSUE TITLE
Firefox w/ 2.0

### ISSUE THREAD

**Issue by kesz1tech** [pipwerks/PDFObject#111]
Hi
I used the code generator and implementation was very easy.  Everything works except FF still shows toolbars, navpanes, etc but I read that 2.0 supports FF browser.  Below is the generated code.  Thanks.

`var options = {
   pdfOpenParams: { toolbar: '0', statusbar: '0', messages: '0', navpanes: '0' }
};

PDFObject.embed(url, "#read-only-file", options);`

**Comment by pipwerks** [comment]
As stated in the docs, the PDF Open Parameters are not supported by all browsers. It's up to browser vendors to support them.

All PDFObject does is embed the PDF into an HTML file using an `<embed>` tag, and provide the ability to easily specify PDF Open Parameters _in case the browser happens to support them_. PDFObject does not polyfill support for PDF Open Parameters.
