### ISSUE TITLE
can not search

### ISSUE THREAD

**Issue by trionfo1993** [pipwerks/PDFObject#112]
can not search, always return 0 result, i think it cause by embed

**Comment by pipwerks** [comment]
Searching a PDF is handled by the browser (and/or PDF renderig plugin), and is outside the scope of PDFObject. All PDFObject does is write an `<embed>` to the HTML page.

If you suspect a problem with the PDFObject JavaScript, you can use pure HTML markup and see if it makes a difference. https://pdfobject.com/generator
