### ISSUE TITLE
Toolbar not hiding only in Firefox

### ISSUE THREAD

**Issue by saikarun** [pipwerks/PDFObject#114]
Hello All,
Requirement: Toolbar should be made hidden (not visible) in FireFox

Below is the code which is working as expected in Chrome and IE but not in Firefox.

Can anyone please let me know any update on the same.

I would be thankful if somebody provides me a codesnippet which is used to load a PDF in an iframe and hides PDF toolbar completely in all browsers.

<!DOCTYPE html>
<html lang="en">
	<head>
		<title>page3</title>
		<meta charset="utf-8" />
		<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.2/jquery.js"></script>
		<script src="js/pdfobject.min.js"></script>
		<script src="js/pdfobject.js"></script>
	</head>
	<body>
		<div id="my-pdf"></div>
		<script>
			PDFObject.embed("pdf/Nagole-Single.pdf", "#my-pdf", options);
			var options = {
		pdfOpenParams: {
			navpanes: 0,
			toolbar: 0,
			statusbar: 0
		}
	};
		</script>
	</body>
</html>

**Comment by pipwerks** [comment]
duplicate https://github.com/pipwerks/PDFObject/issues/99

**Comment by saikarun** [comment]
@pipwerks : Whats the solution available ?? I had tried using open PDF parameters but no luck.. Without providing the solution how can you close the ticket ??

**Comment by pipwerks** [comment]
Please read the statement on PDFObject.com: 
"What PDFObject doesn't do: PDFObject does not magically implement PDF Open Parameters. As mentioned above, these parameters are not widely support. The PDF rendering engine either supports them or doesn't — PDFObject cannot force the rendering engine to implement these features."
