### ISSUE TITLE
It is possible to move buttons (zoom) from right to the left?

### ISSUE THREAD

**Issue by charettedavid** [pipwerks/PDFObject#115]

**Comment by pipwerks** [comment]
Sorry, but this is completely unrelated to PDFObject -- all PDFObject does is embed the PDF into an HTML file using an <embed> tag. Toolbar items are part of the browser's PDF viewer and are controlled by the browser. PDFObject cannot change this. If you really need to customize, you can use PDF.js to render your PDFs, and customize your PDF.js implementation. PDF.js and PDFObject are two unrelated projects.
