### ISSUE TITLE
Fit to page with Chrome

### ISSUE THREAD

**Issue by super-viny** [pipwerks/PDFObject#117]
Hello,

It seems there is an issue to fit the pdf to page with Chrome. The option "fit" works with IE or Firefox but not with Chrome...

Alain

**Comment by pipwerks** [comment]
Please read the docs at http://pdfobject.com. Under "What PDFObject doesn't do:"

"PDFObject does not magically implement PDF Open Parameters. As mentioned above, these parameters are not widely supported. The PDF rendering engine either supports them or doesn't — PDFObject cannot force the rendering engine to implement these features."
