### ISSUE TITLE
Issue With Loading PDF Multiple Times

### ISSUE THREAD

**Issue by NerdGuruDevelopers** [pipwerks/PDFObject#118]
I've currently got a div setup on my page like this:

`<div class="responsive" id="pdf_object"></div>`

I am executing the code below which retrieves a base 64 encoded pdf from my server and uses PDFObject to display it. (response is a json object containing a key 'pdf' with a value like this:  data:application\/pdf;base64,JVBERi0x...

`$.ajax({
	url: '/files/view/' + file.ID,
	type: "POST",
	dataType: "json",
	success: function(response) {
		PDFObject.embed(response.pdf, "#pdf_object");
	}
});`

This piece of ajax works the first time it gets called, however on subsequent executions it displays a blank area where the PDF would be in Chrome version 54.

Do you have any suggestions or tricks to resolve this? Perhaps a forced reload or something?

**Comment by pipwerks** [comment]
Replacing an existing PDF using PDFObject can be done, an example is available here: https://pdfobject.com/examples/replace-PDF-with-second-PDF.html

However this example does not use Base64 PDFs.

For troubleshooting, I suggest refactoring the code to destroy the original element then recreate it before running PDFObject the second time.

It looks like you're using jQuery. If so, you could try something like:

```
var $pdf = $("#pdf_object");
var $pdf_container = $("<div id='#pdf_object_b'></div>");
$pdf_container.insertAfter($pdf);
$pdf.remove();
PDFObject.embed(response.pdf, $pdf_container);
```

This is more long-winded than you'd normally need, but try it for troubleshooting purposes and see if it makes a difference.

**Comment by NerdGuruDevelopers** [comment]
That seems to have fixed it. Thank you. Do you have a donate button?

**Comment by pipwerks** [comment]
Glad you have it working.

Re: donation, appreciate the thought, but nope, no donate button. Feel free to pass it on to a worthy charity. :)
