### ISSUE TITLE
IE 11.576 Reports that browser doesn't support inline PDF's

### ISSUE THREAD

**Issue by desertfoxmb** [pipwerks/PDFObject#125]
The machine does have Adobe Reader installed. When I have that add-on enabled, it works. When I disable that add-on it doesn't. Is this expected?

**Comment by pipwerks** [comment]
PDFObject does not render PDFs, it places the PDF embed code on the HTML page. If the browser does not have a PDF renderer available, the PDF will not be displayed. Chrome, Safari, and Firefox have built-in PDF rendering support, so they will work without plugins. Internet Explorer requires a plugin such as Adobe Reader.

As stated on PDFObject.com:

> IMPORTANT: Browser support for PDFObject does not mean the browser supports PDF embedding! PDFObject only embeds PDFs in browsers that support PDF embedding. Some browsers do not natively support PDF embedding, including Safari for iOS and Internet Explorer. For browsers that do not support PDF embedding, PDFObject provides a way for you to display alternate content. Read below for details.

You can also use PDF.js to force PDF rendering in-browser without a plugin, but that's outside the scope of PDFObject.

**Comment by desertfoxmb** [comment]
Thanks for the quick response. Sorry for taking your time. Been a busy couple days and I missed that bit.

**Comment by pipwerks** [comment]
np, good luck
