### ISSUE TITLE
Firefox 52: PDF not showing up

### ISSUE THREAD

**Issue by jul-** [pipwerks/PDFObject#129]
Hi,

I am using the most recent version of the plugin PDFObject for my print preview. Since Firefox52 the PDF is not showing up. The message "This browser does not support inline PDFs.... " shows up. In my imagination the FF built-in pdf viewer should be opened.

My embedding looks like:

`PDFObject.embed(url, "#preview");
`

Where is the mistake?

Thanks and Greetings
Julian

**Comment by knubew** [comment]
I've had the same problem with Firefox 52. Now I use PDFObject 2.0.x with a fallback to PDFJS. It works fine.
`<body>
<div id="pdf"></div>
<script src="/js/pdfobject.min.js"></script>
<script>
	var options = {
		PDFJS_URL: "/pdfjs-dist/web/viewer.html"
	};
	var myPDF = PDFObject.embed("/myExample.pdf", "#pdf", options);
</script>
</body>`

**Comment by jul-** [comment]
Hmm ok, thanks.

But there is no way to use the built-in pdf viewer?

**Comment by knubew** [comment]
> But there is no way to use the FF built-in pdf viewer?

Using PDFObject I did not find another way. may anyone else out there ???
If you use just a normal HTML link or a JavaScript 'locatio..href = xxx.pdf'' to a pdf the built.in viewer of FF works well.

**Comment by pipwerks** [comment]
See https://github.com/pipwerks/PDFObject/issues/93
