### ISSUE TITLE
Is there way to use blob (.pdf) response obtained from ajax POST Request to view as a pdf in IE.?

### ISSUE THREAD

**Issue by ArjunaPuttappa** [pipwerks/PDFObject#130]
While we tried customizing embed function, we are getting Access denied popup in IE and Reload popup in Chrome.

suggest me the solution if u guys have gone through this kind of issues.

Thanks in Advance.

**Comment by pipwerks** [comment]
When you boil it down, all PDFObject does is write an `<embed>` to the page. If your PDF works when it is embedded using static markup, it should work with PDFObject. Try using the static markup generator to test your blob. https://pdfobject.com/generator
