### ISSUE TITLE
fill form

### ISSUE THREAD

**Issue by aldo-t** [pipwerks/PDFObject#132]
Hi,
i'd like to fill pdf form and after i'd like to save changes. 
Is it possibile?
Thanks.
Regards.

**Comment by pipwerks** [comment]
That type of functionality is handled by the PDF rendering engine (either native browser PDF support or a plugin like Adobe Reader). PDFObject simply embeds the PDF on the page, the PDF rendering engine, which is independent of PDFObject, handles the rest.
