### ISSUE TITLE
Initial View does not work

### ISSUE THREAD

**Issue by 1Map** [pipwerks/PDFObject#133]
I tried with:
`pdfOpenParams: {
        view: "FitH"
},
fallbackLink: '<p>This browser does not support inline PDFs. Please download the PDF to view it: <a target="_blank" href="[url]">Download PDF</a></p>',
PDFJS_URL: "/javascripts/pdfjs/web/viewer.html"`

but it keeps on loading with "Automatic Zoom" as the default view

I even tried `view: "FitV"` but no difference.  Same result.

**Comment by pipwerks** [comment]
Each PDF rendering engine handles PDF Open parameters differently; some don't support the parameters at all. Unfortunately this is beyond the control of PDFObject. If you're using PDF.js to render the PDF, it should work fine -- try looking at the code in this example: https://pdfobject.com/examples/pdfjs-forced-with-querystring.html

**Comment by pipwerks** [comment]
Actually, I see in my sample it also goes to "Automatic Zoom". I guess this is how PDF.js handles it now. Not much we can do about it.
