### ISSUE TITLE
PDF Open Parameters with base64

### ISSUE THREAD

**Issue by RecepSenel** [pipwerks/PDFObject#134]
Hello,

the open parameters doesn't work with base64. For example:

```
base64="data:application/pdf;base64,JV..."

var options = {
		pdfOpenParams: { view:"FitH" }
	};
PDFObject.embed(base64, "#iframe", options);
```

the result is : `"data:application/pdf;base64,JV...#view=FitH"` and this is an invalid base64 code.

`PDFObject.embed(static.pdf, "#iframe", options)`; works.

Any ideas how to use open parameters with base64?

Best Regards

**Comment by pipwerks** [comment]
Open Parameters (which, bear in mind, are not supported equally by all PDF rendering engines) requires using the hash (#) before specifying parameters. Unfortunately, I don't think there's any way around it.
