### ISSUE TITLE
PDFOject in Chrome does not have text search functionality

### ISSUE THREAD

**Issue by gvrameshreddy** [pipwerks/PDFObject#135]
In Chrome browser PDFObject opens fine. But using Ctrl+F we are not able to search the text with in the PDF. In Internet explorer it opens another Find Text with in PDF to search for the text. This does not work in Chrome Browser. Any workaround for this.

**Comment by pipwerks** [comment]
No bearing on PDFObject. Search and other functionality is provided by the PDF rendering engine, not by PDFObject. You'd need to check with the browser vendor for details about their PDF rendering engine.
