### ISSUE TITLE
Force Firefox option

### ISSUE THREAD

**Issue by zslabs** [pipwerks/PDFObject#139]
Building off of the discussion on https://github.com/pipwerks/PDFObject/issues/93#issuecomment-313800360, I'd like to propose adding an option to force Firefox to render inline PDFs. This is an exception since the current implementation checks against mime-type; and as explained on the documentation site - is something that doesn't jive with Firefox right now.

One option I had proposed was using feature detection, but as @pipwerks mentioned, Firefox is not shy about removing features at-will, so I 100% agree that approach may not be the best option. I think if we were able to find a more reliable UA sniffer, that would provide a way for users (knowing the potential drawbacks) to force inline rendering in Firefox based on their viewer-base.

**Comment by bcalik** [comment]
I can confirm this guy's fork is working well on Firefox:
rhinogram/PDFObject@ba4a15a

**Comment by pipwerks** [comment]
The method being used for Firefox detection in this thread is definitely not future-proof. As we've learned the hard way, Mozilla is updating Firefox at a pretty rapid pace, and has no qualms throwing out old stuff. One of their biggest initiatives is improved privacy by making it hard to fingerprint the browser. This is what broke PDFObject in the first place, as one of the key ways to fingerprint a browser is to sniff for plugins -- Mozilla removed the flags for plugin support. A proprietary feature such as InstallTrigger would be next on the list, so I imagine they'll be changing it in the near future. Unfortunately we're left with browser sniffing, as repugnant as it may be.
