### ISSUE TITLE
Pdf File is not opening in IE edge

### ISSUE THREAD

**Issue by bhushan-kollepara** [pipwerks/PDFObject#141]
Hi team,
I am using pdfobject to open a pdf file with in application using object , It is working in chrome and FF, But it isnot opening in IE. I am getting below this error : [Initialise---[] 
![ieerror](https://user-images.githubusercontent.com/27730202/28456407-d18531e2-6e1f-11e7-8595-5dd1b6f1fbf7.PNG).

below is the my object in HTML
<div id="MypdfDiv" style="display: none;">
      <object data="{{pdfAsDataUri}}" type="application/pdf" data-caption="original"></object>
    </div>

My Js Scirpt:
$scope.pdfAsDataUri = "data:application/pdf;base64,"+pdfData.responseData;
PDFObject.embed($scope.pdfAsDataUri, "#MypdfDiv");

Thanks,
Team

**Comment by pipwerks** [comment]
Sorry, but whatever is happening there is independent of PDFObject -- that screen is being generated by your browser, not by PDFObject. If you search the repo issues, you will see others have had issues with IE rendering base64 as well.

**Comment by bhushan-kollepara** [comment]
Hi Team,
Could you post some sample code for IE? that will help to me to overcome this issue.

Thank you...
