### ISSUE TITLE
Stuck on loading in Safari 10.1.1

### ISSUE THREAD

**Issue by ChrisGrigg** [pipwerks/PDFObject#143]
Hi,

I have an issue where a PDF gets stuck on loading in Safari 10.1.1. This has been reported on one machine so far.

    const pdfObjectOptions = {
        fallbackLink: "<p>This browser does not support inline PDFs. Please download the PDF to view it: <a class='external-link' href='[url]'>Download PDF</a></p>"
    };
    $('#viewAttachment').on('change', function () {
        PDFObject.embed(this.value, '#pdfViewer',pdfObjectOptions);
    });

Thanks

![screen shot 2017-08-11 at 6 22 54 pm](https://user-images.githubusercontent.com/3083238/29239039-41684ca2-7f3b-11e7-8256-d1bd823d4254.png)

**Comment by pipwerks** [comment]
All PDFObject does is write the HTML `<embed>` code to the page. As with plain HTML, PDFObject does not have any control over loading the PDF, or the server serving the PDF. 

I'm guessing one of several things is happening: the server didn't fully serve the doc, the doc is corrupted, or there's something in the PDF that the PDF viewer is not able to handle (e.g. advanced forms or multimedia embedded within the PDF). In all of these cases, PDFObject has no control or influence over how the browser and/or PDF renderer handles the PDF.

Best I can suggest is to clear the cache and try again. If the problem persists, try a different PDF. You can also bypass the browser's native PDF handler and force the browser to use PDF.js (which is unrelated to PDFObject).
