### ISSUE TITLE
Pass PDF link as URL parameter

### ISSUE THREAD

**Issue by dovematrix** [pipwerks/PDFObject#144]
Is it possible to display a PDF using PDFObject by passing the PDF link as a URL parameter such as these?

https://pdfobject.com/examples/replace-PDF-with-second-PDF.html?file=https://pdfobject.com/pdf/sample-3pp.pdf

or 

https://pdfobject.com/examples/replace-PDF-with-second-PDF.html?file=https://pdfobject.com/pdf/sample.pdf

If so, could you provide an example?

Thanks

**Comment by pipwerks** [comment]
Hello. PDFObject support querystrings. Please see the [examples](https://pdfobject.com/#examples), specifically https://pdfobject.com/examples/querystring-URL.html

    PDFObject.embed("/pdf/file.php?item=sample-3pp", "#my-pdf");

This is assuming the URL with the querystring points directly to a PDF file and the server serves the file with the correct MIME type.
