### ISSUE TITLE
Inject CSS skin to PDF.js

### ISSUE THREAD

**Issue by aetna-softwares** [pipwerks/PDFObject#145]
Hi,

Looking at PDF.js official documentation, they said that we should not use the default skin of the viewer when embed in a website.

I used to inject CSS file in the PDF.js viewer iframe to separate my CSS skin and the official viewer code for easily upgrade PDF.js for bugfix/new version.

But now I wish to use PDFObject that is a better approach than juste PDF.js viewer only and I am stuck with the skin injection. Is it possible to add an option to PDFObject to inject a CSS file to PDF.js iframe ?

Or if the option seems to be too exotic request, can you point me a way to interact with PDFObject to know when a PDF.js iframe has been injected (is there some kind of event somewhere that I can rely on ?)

**Comment by pipwerks** [comment]
PDFObject has no relation to PDF.js or its skins. Sorry.
