### ISSUE TITLE
PDFObject overlaps fixed elements in IE11

### ISSUE THREAD

**Issue by sernaashui** [pipwerks/PDFObject#146]
Here is a screenshot of this issue on the PDFOBject page.

All I did was add { position: fixed; width: 100% } to the header.

![image](https://user-images.githubusercontent.com/21209525/29577682-358ee484-8721-11e7-881b-27416f1a702a.png)

**Comment by pipwerks** [comment]
I'm guessing you're using the Adobe Reader plugin. Is this Internet Explorer?

Some browsers will insert plugin-type content (Flash, embedded PDFs) on top of all page content, regardless of z-index. See this StackOverflow post for a decent explanation of IE's behavior. https://stackoverflow.com/a/12977151/124084

In my quick test, the PDF displays under the header correctly in Chrome and Safari. If you really need to force the PDF to display underneath HTML content in IE, you may want to force the page to render the PDF using PDF.js (at least for visitors using IE).

**Comment by sernaashui** [comment]
Thank you so much for your quick response!

Yes, delivering to IE is a must since the majority of our traffic (sadly) is from IE. Thank you for the link to the post on IE’s handling of windowless and windowed elements.

I had actually read into that, but couldn’t find how it applied to <embed> tags, which PDFObject uses.
However, I just tested the solution that the post outlined and it does indeed work in IE11 for fixed headers. It is horribly ugly, though. haha

I may have to look at the PDF.js option.

Thanks again!
