### ISSUE TITLE
 use your own copy of PDF.js and PDFObject's forcePDFJS option (this is a sledgehammer technique). Hopefully Mozilla will reverse their decision

### ISSUE THREAD

**Issue by pimpedoutgeek** [pipwerks/PDFObject#147]
Please update your doco on how you accomplish FF PDF display without issues [forcePDFJS](https://pdfobject.com/examples/pdfjs-forced.html). Code examples would be great.

**Comment by pipwerks** [comment]
Not sure what you're asking, the example you pointed to works fine, and you have not specified any issues.
