### ISSUE TITLE
Cannot open pdf file in IE 11

### ISSUE THREAD

**Issue by wangjunqin** [pipwerks/PDFObject#148]
<!DOCTYPE html>
<html>
<head>
    <title>网页嵌入pdf浏览器</title>
    <script type="text/javascript" src="./pdfobject.min.js"></script>
    <style type="text/css">
        .pdfobject-container { height: 600px;}
        .pdfobject { border: 1px solid #666; }
    </style>
</head>
<body>
<div id="example1"></div>
<script type="text/javascript">
    PDFObject.embed("./1.pdf", "#example1");
</script>
</body>
</html>

the pdf cannot display

**Comment by wangjunqin** [comment]
I have installed adobe reader 9

**Comment by pipwerks** [comment]
Your code does not include an element with the ID example1. Please follow the examples on pdfobject.com.
