### ISSUE TITLE
Disable Right Click inside viewer

### ISSUE THREAD

**Issue by KevinTemes** [pipwerks/PDFObject#149]
Hello there!

I downloaded the plugin and managed to display my pdf files correctly. Now what i need to do is to prevent users from downloading such files as much as i can. I already managed to hide the toolbar in the viewer, but they will still be able to download the document just by right-clicking it. Is there any way to disable right click on the embed element generated by the plugin?

Thanks in advance.

**Comment by pipwerks** [comment]
Hi Kevin. Disabling right-click will not prevent people from being able to save the PDF to their hard drives; PDFs are usually downloaded to disk (browser cache), so they already have a copy whether they know it or not. Most browsers provide a built-in PDF rendering engine which includes a "save" button, and there is no way to hide or disable this button. If you want to prevent people from downloading or saving the PDF, you need to use something like Flash Player, which doesn't render a PDF in its native format, or proprietary DRM technology such as Adobe Editions. Good luck
