### ISSUE TITLE
pdfobject.com site down? Move documentation here?

### ISSUE THREAD

**Issue by timschwallie** [pipwerks/PDFObject#150]
Is the site down?
Might be time to move site content and the documentation to here.

**Comment by pipwerks** [comment]
Server update. Should be restored today. It doesn't impact the availability of the script, which are hosted here and on NPM.

I will not move the documentation or examples here so long as I am unable to run ads on GitHub. No one likes ads, and I only make a few bucks, but it's helpful for paying my server costs.

**Comment by pipwerks** [comment]
FYI, the site has been refreshed and migrated to GitHub pages. No ads.
