### ISSUE TITLE
Website redirects to something else??

### ISSUE THREAD

**Issue by plasmarocker** [pipwerks/PDFObject#151]
http://pdfobject.com directs me to a different website... I want to use the library for a project, but samples and docs only seem to reside on an unreachable website at the moment. Sorry if you're already aware and are working on this.

**Comment by pipwerks** [comment]
Yeah, the server that hosts pdfobject.com also hosts other sites and is currently borked (hence the odd redirect and site unresponsiveness). Hopefully this will be resolved soon, sorry for the inconvenience.
