### ISSUE TITLE
Has anyone knows how to get the current page in pdfobject.js

### ISSUE THREAD

**Issue by kouwoo** [pipwerks/PDFObject#152]
Has anyone knows how to get the current page in pdfobject.js

**Comment by pipwerks** [comment]
Not possible with the most common PDF rendering engines -- they don't expose that information. You can probably do it with PDF.js, but that would require rendering all of your PDFs with PDF.js. (PDF.js is not related to PDFObject)

**Comment by kouwoo** [comment]
thanks
