### ISSUE TITLE
PDF embedding using pdfobject is not working on chrome on iOS

### ISSUE THREAD

**Issue by maheshkelkar** [pipwerks/PDFObject#154]
I tried pdfobject for PDF embedding on chrome on iOS (iphone). The fallback link showed up. However, when I click on "download PDF", nothing happened. 

Same process happened on safari, but the PDF opened up in another, on a click on "download PDF".

**Comment by pipwerks** [comment]
The fallback link is just a link to the PDF file. Whether the PDF properly displays or downloads depends on a number of factors, including how the server handles PDFs and how the browser handles PDFs. All PDFObject does is provide the link as an HTML `<a>` tag. The rest is outside the scope of PDFObject.
