### ISSUE TITLE
[PDFObject] Target element cannot be determined

### ISSUE THREAD

**Issue by eldhobai** [pipwerks/PDFObject#155]
When i use pdfObject in my PHP page it shows an error like 
[PDFObject] Target element cannot be determined
and the pdf file didnt display
please help

thanks

**Comment by pipwerks** [comment]
Hello. This area is for posting bugs, and is not a general help forum. All I can recommend is to look at the examples at pdfobject.com. Note PDF is a client-side (HTML/JS) script, not server-side (PHP). Be sure the target element exists before trying to invoke PDFObject.
