### ISSUE TITLE
IE9 sometimes dont download PDF files

### ISSUE THREAD

**Issue by caarlos0** [pipwerks/PDFObject#16]
Sometimes, IE9 dont download the file.

The request stay by 2minutes in a "pending" status, and then it works... but, man, 2 MINUTES is too much time.

I've fixed it in my fork, using a iframe in the place of object for ie9.

what the possible problem that this may cause?

**Comment by pipwerks** [comment]
Thanks for the info. I know it's a bit late, but I am working on updates to fix issues with IE and more.
