### ISSUE TITLE
Is there a functionality to do search in a pdf?

### ISSUE THREAD

**Issue by aamirkhurshid** [pipwerks/PDFObject#161]
var options = {
              

 height: "400px",
    page: '2',
    pdfOpenParams: {
        view: 'FitV',
        pagemode: 'thumbs',
        search: 'lorem ipsum'
    }
};

PDFObject.embed("/pdf/sample-3pp.pdf", "#my-container", options);

**NOT WORKING.......................................**

**Comment by pipwerks** [comment]
As stated on PDFObject.com: "Warning: These [pdfopen params] are proprietary and not well supported outside of Adobe products. Most PDF readers support the page parameter, but not much else. PDF.js supports page, zoom, nameddest, and pagemode."
