### ISSUE TITLE
Fails to render with data URL for large file

### ISSUE THREAD

**Issue by bbbneo333** [pipwerks/PDFObject#167]
```javascript
const target: DataTransfer = <DataTransfer>(evt.target); // evt via file selection dialog
const file = target.files[0];
// init reader
const reader: FileReader = new FileReader();
// invoked on file load end
reader.onloadend = (e: any) => {
  // finished loading file
  PDFObject.embed(e.target.result, '#proposalPreview', {
     height: '40pc',
     pdfOpenParams: {
       view: 'FitV'
     }
  });
};
// invoke reading process
reader.readAsDataURL(file);
```

I can see that DOM is being rendered properly:
![chrome_2018-08-15_14-02-00](https://user-images.githubusercontent.com/23015711/44139190-fd4a5a62-a093-11e8-8689-5cd7b9bf37b7.png)

I can also see that the `div` within which I want to embed my PDF is also being rendered properly (the given `height` and `width` is in place), but nothing's in that `div`, just blank. The module does the job perfectly when file size is under `2-3 Mb`.

While I was researching for this issue, I found out that using data URLs for large files is not recommended. Is that the thing here?

Using: Chrome 68.0.3440.106
On: Windows 10

Thank you.

**Comment by bbbneo333** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=569888

**Comment by bbbneo333** [comment]
So instead of loading payload via `FileReader.readAsDataURL`, I tried `window.URL.createObjectURL` and it worked for me. Turns out that data URL has its own set of length limitations.

**Comment by pipwerks** [comment]
Thanks for providing the link and details
