### ISSUE TITLE
PDFobject.js - "Failed to load document" chrome version 69.0 inline pdf viewer

### ISSUE THREAD

**Issue by manishchhugani** [pipwerks/PDFObject#170]
Hi,
I am trying to load pdf from a different domain in chrome but it is giving me error saying "Failed to load pdf document". But the same thing works in IE edge and Mozilla.

I used <embed> to work with different version of browsers but ending up getting same error for chrome
&lt;embed id="printThis" src="../view.html" type="application/pdf" style="overflow: auto; width: 100%; height: 100%;"&gt;.

I even tried to check with current browser (chrome- ture/false) using following code and tried to use an <object> for chrome instead of <embed>, but still it did not work for me.  
var isChrome = (function () { return (/Chrome/.test(navigator.userAgent) && /Google Inc/.test(navigator.vendor)); })();

Can you please explain how should I code so that I can force chrome browser to view my pdf?

**Comment by pipwerks** [comment]
Hi @manishchhugani 

I'm sorry you've run into difficulties, but please note this issues area is for reporting bugs and problems with the PDFObject utility, not for implementation support. 

Chrome supports PDFs that load from other domains. 

Also note that PDFObject will never generate an error with the phrase "Failed to load PDF document". If you are seeing this error, it means PDFObject is working as expected (writing the `<embed>` to the HTML page), and the browser is encountering an issue loading the remote file. This would be a browser issue beyond the scope of PDFObject.

If you feel you have uncovered a PDFObject bug or edge case, please feel free to provide more information -- screenshots and links to live site(s) appreciated.

Thanks
