### ISSUE TITLE
Disable font-face

### ISSUE THREAD

**Issue by sscaff1** [pipwerks/PDFObject#176]
PDFJS allows you to specify the option disableFontFace. I keep getting CSS3111 errors associated with font-faces in IE11. Is there a way to include this option?

**Comment by pipwerks** [comment]
PDFObject only supports [PDFJS's querystring options](https://github.com/mozilla/pdf.js/wiki/Viewer-options). `disableFontFace` is an API option in PDFJS and is not something that can be specified via URL/querystring. You'd have to customize your PDFJS viewer.html implementation, which is outside the scope of PDFObject.

Good luck
