### ISSUE TITLE
Firefox 65: PDFObject.supportsPDFs false positive

### ISSUE THREAD

**Issue by mhulse** [pipwerks/PDFObject#180]
Using Browserstack, and Windows 7 and 10/Firefox 65, I get a `true` when using `PDFObject.supportsPDFs` and PDF window shows but no PDF loads.

I was not able to find definitive answer in the issues ... Anyone know of a workaround?

### Steps to reproduce

Visit https://pdfobject.com/ in Firefox 65/Windows 7 and 10 and the embedded PDF at top of page will be blank.

**Comment by mhulse** [comment]
Also noticing that Firefox 65 on macOS Mojave is showing a blank spot where PDF should appear:

![Screen Shot 2019-03-13 at 3 53 15 PM](https://user-images.githubusercontent.com/218624/54319828-23441f00-45a8-11e9-892e-fd5743ab2142.png)

When I visit [detection page](https://pdfobject.com/examples/detection.html) I get:

> This browser supports inline PDFs

I'm wondering if this is a Browserstack thing? Or, did Firefox change something?

Interestingly, when I test Firefox 62, the PDF shows, but 63+ I get blank screen and false positive.

Can anyone point me towards changelog, or similar, where this feature was turned off?

**Comment by mhulse** [comment]
I just looked into using PDFjs and that fixed the issues in Firefox. Surprisingly, implementation was very easy thanks to this PDFObject example page:

https://pdfobject.com/examples/pdfjs-forced.html

Going to close this issue.

**Comment by pipwerks** [comment]
Hi @mhulse 

Sorry for the delayed response. Firefox uses PDF.js as its default rendering engine, you shouldn't need to implement your own copy of PDF.js just to render a PDF in Firefox.

I have checked Firefox 65.0.1 in Mojave, and the PDF on the pdfobject.com home page loads correctly. It may have just been a Browserstack issue.

**Comment by mhulse** [comment]
Hi @pipwerks, thanks so much for your reply and help! I'm sure you are busy and I apologize for creating noise over here.

> Sorry for the delayed response. Firefox uses PDF.js as its default rendering engine, you shouldn't need to implement your own copy of PDF.js just to render a PDF in Firefox.

Oh really? That's interesting! I did not know that was the case. Thanks for shedding light.

> I have checked Firefox 65.0.1 in Mojave, and the PDF on the pdfobject.com home page loads correctly. It may have just been a Browserstack issue.

Yah, I get same result on my Mac too.

Strangely, in BrowserStack, Firefox <= v62 do display embedded PDFs. 63 and above show blank spot and give false positive for PDF support.

The reason why I looked into this, was a client had mentioned that they did not see PDF show (just blank spot) in Firefox on Windows 7, Firefox 65.

Looking at the application settings in the prefs, they look the same:

### Firefox 62, Windows 7

![Firefox 62, Window 7](https://user-images.githubusercontent.com/218624/54380299-58a04980-4648-11e9-96ee-035b5574d6ce.png)

### Firefox 63, Windows 7

![Firefox 63 - Windows 7](https://user-images.githubusercontent.com/218624/54380345-6a81ec80-4648-11e9-86c0-cea7cf5a68cb.png)

Interestingly, the default reader is Acrobat? 🤷‍♂️ 

I think you're right that it's a BrowserStack thing, but what throws me, is a client reported the same issue about Windows 7, Firefox (latest I think).

Anyway, this is all probably a wild goose chase, so ignore my ramblings...

Thanks for replying and for the help!!!

**Comment by pipwerks** [comment]
See https://github.com/pipwerks/PDFObject/issues/185 for some additional info.

Just a note on this: Firefox uses PDF.js by default, but if you select "always ask" or "Save file" in your preferences (as in your screenshot above), you're effectively turning off PDF.js support. Since PDFObject **assumes** PDF.js is available in Forefox, it will fail if the user has changed their preferences to anything other than "Preview in Firefox". Unfortunately there is nothing I can do about it, as Mozilla has made sniffing PDF support impossible in Firefox, in order to increase privacy and reduce browser fingerprinting.
