### ISSUE TITLE
Is it possible to enable Hand Toolbar on load?

### ISSUE THREAD

**Issue by Titannet** [pipwerks/PDFObject#184]
Hi,

I would like the handtool to be on as the default setting, rather than people having to access it via clicking on the button.

Is it possible? Thx for answer.

**Comment by pipwerks** [comment]
Toolbars are controlled by the PDF reader functionality within the browser (or plugin like Adobe Reader). PDFObject has no control over this aside from using `pdfOpenParams` as specified in the PDFObject docs.
