### ISSUE TITLE
Dont work in firefox??

### ISSUE THREAD

**Issue by Garoh** [pipwerks/PDFObject#185]
Im use ff 66.0.5 (64-bit) in OS 10.14.4

**Comment by pipwerks** [comment]
Works fine for me, macOS 10.14.5, FF 67.

**Comment by rippo** [comment]
Nope can confirm doesn;t work in FF on a PC

even your home page https://pdfobject.com/

**Comment by pipwerks** [comment]
I just confirmed it works in Windows 10, with the latest version of Firefox.

Can you please be specific about what version of Windows and Firefox you're using? There may be other factors at play.

**Comment by rippo** [comment]
FF 67.0.4 x64  (says up to date)
Windows 10 Pro, Version 1809, OS build 17763.592

If I go to you home page it looks like this (works in chrome)...

![image](https://user-images.githubusercontent.com/772549/60491330-70a3e380-9ca0-11e9-9ffd-4cbbac270c4f.png)

**Comment by pipwerks** [comment]
Thanks, I'll take a look as soon as I get a chance.

**Comment by robban** [comment]
I have the same issue on MacOS High Sierra , Firefox 70.0 (64 bit) . The examples on pdfobject.com do not work and empty white area as in above screenshots are shown.

**Comment by bschantz** [comment]
If the handling option in about:preferences for Portable Document Format (PDF) is set to anything but 'Preview in Firefox', then pdf using <object> or <embed> tags won't display, nor will they provide an error.

**Comment by bschantz** [comment]
If the handling option in about:preferences for Portable Document Format (PDF) is set to anything but 'Preview in Firefox', then pdf using `<object>` or `<embed>` tags won't display, nor will they provide an error.

**Comment by bschantz** [comment]
It's a known bug in Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1500404
