### ISSUE TITLE
bookmarks

### ISSUE THREAD

**Issue by TharunMaddu** [pipwerks/PDFObject#186]
1. I keep the options for pagemode as **thumbs** and even tried keeping **none**, still the page was showing bookmarks.

2. Not supporting in Firefox,,

3. Sample snippet
const options = {
        pdfOpenParams: {nameddest: 'Attachments', view: 'FitH', pagemode: 'thumbs', toolbar: '1'}
      };
      const mynode = document.getElementById('example');
      PDFObject.embed('file.pdf', mynode, options);

I dont want to see the bookmarks at all,,

**Comment by pipwerks** [comment]
Toolbars are controlled by the PDF reader functionality within the browser (or plugin like Adobe Reader). PDFObject has no control over this aside from passing `pdfOpenParams` as specified in the PDFObject docs.
