### ISSUE TITLE
Is it possible to zoom the embedded PDF by pinch?

### ISSUE THREAD

**Issue by tianzhich** [pipwerks/PDFObject#187]
The local PDF file opened by Chrome can using pinch to zoom. The Chrome also using `<embed>` tag to do this. 
But even when I embed the PDF full-browser just like the default behavior of Chrome. Pinching is not working.

**Comment by pipwerks** [comment]
PDFObject only embeds the PDF into the HTML. The browser (and/or PDF rendering plugin like Adobe Reader) is responsible for functionality such as pinch to zoom, PDFObject has no control over that type of functionality.
