### ISSUE TITLE
Is there any way to access the elements embedded?

### ISSUE THREAD

**Issue by varunrayen** [pipwerks/PDFObject#188]
Once a PDF has been embedded in a HTML element, is there a way to access the content of the embedded HTML elements?

Kindly assist!

**Comment by pipwerks** [comment]
Hello. When you say "the embedded HTML elements", let's be clear that PDFObject does NOT convert PDFs to HTML. The PDF remains a PDF. As such, no, there is no browser API for interacting with a PDF's content, and PDFObject can't help you there.

If you choose to embed the PDF using PDF.js -- a completely different library and unrelated to PDFObject -- the PDF content will be rendered as HTML. I can't speak to how you can interact with a PDFJS file, you will need to refer to the PDFJS docs.
