### ISSUE TITLE
Browser started to download the pdf file

### ISSUE THREAD

**Issue by ibrahimozgon** [pipwerks/PDFObject#189]
Hello,
Recently we started to have this error, it was working fine before. 
We try to display pdf in a bootstrap modal. 
This is the html template in angular. We pass url of the pdf in attch.location:
`
<span *ngFor="let attch of comm.attachments" class="email-attachment" (click)="goToAttachment(attch.location)"><i class="fa fa-paperclip"></i></span>
`

This is the function we call from angular template(I removed not related code to make clearer):
`
goToAttachment(attachment) {
      $("#file-display").html("<img id='image-object' class='draggable' src='" + attachment+ "' style='position: relative;'/>")
 PDFObject.embed(attachment, "#pdfResult")
  }
`
Any behavior changed in chrome? Why this problem started? Any help is appreciated, thank you.

 
![image](https://user-images.githubusercontent.com/3949722/64543692-57698400-d32e-11e9-9c64-e2282bc10e87.png)

**Comment by RichFeimer** [comment]
I've been having the same issue. Instead of displaying pdfs, it just downloads them.

**Comment by onkiit** [comment]
same issue here. currently solved by changing `form-data` to `inline`, inside my `Content-Disposition` headers

**Comment by pipwerks** [comment]
PDFObject does not control whether or not the PDF is downloaded vs embedded in the web page. As @onkiit mentioned, this is handled on the server via the content-disposition header. Be sure to have the header set correctly on the server (usually to 'inline' and not 'attachment').

**Comment by ertemmstein** [comment]
For azure blobs you need to add those 2 parameters
![image](https://user-images.githubusercontent.com/5495357/147940420-d20eb5aa-faff-4f98-ada4-746835676a29.png)

**Comment by SHOrTEVA** [comment]
@onkiit thanks for the insight.
Same issue. But it's works on Firefox but not on Chrome. Currently solved by changing the string "attachment" to "inline" in the PDF file download URL. 😂I finally realize that I don't need to emerge a pdf viewer.
