### ISSUE TITLE
Open pdf in base64

### ISSUE THREAD

**Issue by JoseDRojasA** [pipwerks/PDFObject#190]
Is it possible to display a pdf encoded in base64? 
If it is, Could you give an implementation example?

**Comment by ajthenewguy** [comment]
Instead of passing the URL to .embed(), pass "data:application/pdf;base64," + the base64.
eg.
`PDFObject.emebed("/path/to.pdf")` becomes `PDFObject.embed("data:application/pdf;base64,bA64c041341...")`

**Comment by stla** [comment]
Indeed that works but it seems that the `pdfOpenParams` options do not work.

**Comment by rps-repo** [comment]
As stated above this works but I found a couple of issues.  Not sure if there is any way to fix.
The name of the pdf is shown as "data" in top left and when the download link is clicked the file name is set as "download".  When using a URL the file name in the url is shown in both places.

**Comment by pipwerks** [comment]
https://pdfobject.com/examples/base64.html
I added a link to this example on the pdfobject.com home page. 
Thanks

**Comment by felipeallmountain** [comment]
Thanks for the sample!!, however, can you share the source for that sample please?? thx!!

**Comment by pipwerks** [comment]
The source for the base64 PDF? It's just https://pdfobject.com/pdf/sample.pdf

**Comment by felipeallmountain** [comment]
I mean, the source of implementation, or is the same as `PDFObject.embed("data:application/pdf;base64,bA64c041341...")`?

**Comment by pipwerks** [comment]
The base64 string is just the PDF I linked to above, after running through a base64 converter. Download the PDF, run it through an online PDF-to-base64 converter, and it gives you a string representaion of the PDF.

The rest of the example's code is viewable via view-source in the HTML file.
