### ISSUE TITLE
Edge not displaying PDF properly when created with createObjectUrl

### ISSUE THREAD

**Issue by jdmerinor** [pipwerks/PDFObject#191]
Hi Guys,

I'm trying to display a PDF created with URL.createObjectURL(blob) but it's working on all browser excepting Edge. I'm getting instead an error that says "Couldn't open PDF" "Something's keeping this PDF from opening" I created a sandbox to show the problem:

sandbox: https://codesandbox.io/s/pdfobject-not-working-edge-b6egv
actual app link (required for displaying the PDF since it doesn't work in the sandboxed iframe of the sandbox): https://b6egv.csb.app/

Thanks and I would really appreciate any ideas or help with this :)

**Comment by pipwerks** [comment]
I can't speak to PDFObject's usage in a React project.

Broadly speaking, blob support is browser-dependent, and has been an issue for others in the past, esp w Microsoft browsers. Try replacing the blob URL with a traditional URL (direct pointer to a PDF file) to verify whether the blob is the issue.

I'm going to close this issue as it's not a PDFObject bug.

Good luck

**Comment by jdmerinor** [comment]
I never mentioned React really so I'm not sure what do you mean with that hehe.

I checked and it will work without the blob url. But then I tried creating an iframe from scratch (not using pdfObject) and it works, so I think pdfObject can probably be improved to support this case since it's actually possible and supported this way by Microsoft Edge.

I updated the sandbox to show the idea of the iframe. Let me know what do you think :)

sandbox: https://codesandbox.io/s/pdfobject-not-working-edge-b6egv
actual app link (required for displaying the PDF since it doesn't work in the sandboxed iframe of the sandbox): https://b6egv.csb.app/
