### ISSUE TITLE
Passing custom HTTP headers

### ISSUE THREAD

**Issue by amcsi** [pipwerks/PDFObject#192]
How can I pass HTTP headers for the PDF request? Specifically Authorization with a bearer token.

Alternatively if that is not possible, what's the recommended way to implement security so that guests couldn't read the PDFs?

**Comment by pipwerks** [comment]
Apologies for the delayed response, I have not been receiving notifications for some reason.

You can pass URL parameters via PDFObject, but PDFObject does not specify headers. PDFObject is purely a client-side script for embedding PDFs into web pages. Headers are outside the scope of PDFObject. Sorry.
