### ISSUE TITLE
PDF forms submission

### ISSUE THREAD

**Issue by k2mol** [pipwerks/PDFObject#193]
When I use a form document I can fill in the form but nothing happens when clicking the submit form buttons that can be included in pdf documents. Is there a way to fix this?

**Comment by pipwerks** [comment]
Apologies for the delayed response, I have not been receiving notifications for some reason.

PDFObject is just a simple script for embedding PDFs into HTML documents, it does not have any control over the contents of PDFs. Sorry.

If you are having issues submitting a form embedded in a PDF, I suspect it has something to do with the PDF viewer you are using. For example Adobe Reader contains many advanced functions that are not supported in native PDF rendering engines like Preview on a macOS or the native PDF rendering in browsers like Chrome or Firefox.
