### ISSUE TITLE
How to set width and height using PDFjs?

### ISSUE THREAD

**Issue by berrynana** [pipwerks/PDFObject#195]
I try below code. but can not set these style attribute.

PDFObject.embed("myfile.pdf", "#my-container", {width: '500px', height: "20rem", forcePDFJS: true, PDFJS_URL: "../pdfjs/web/viewer.html"});

help me.

**Comment by pipwerks** [comment]
Apologies for the delayed response, I have not been receiving notifications for some reason.

There is a functional example of a pdfJS embed with specific width and height here: https://pdfobject.com/examples/pdfjs-forced.html
