### ISSUE TITLE
Safari OSX does not load PDF served via a 302 redirect

### ISSUE THREAD

**Issue by johnhunter** [pipwerks/PDFObject#196]
**PDFObject version:** 2.1.1
**Browser:** Safari 13.0.3 (OSX)

**Steps:**

1.  Create a page that loads a PDF using `PDFObject.embed`
2. Host page on https server
3. Setup a 302 redirect on the PDF file url passed to the embed method - redirects to a real pdf file

**Expected:**

All browsers display the PDF in the page

**Actual:**

Chrome, Firefox, IE11 (with plugin) display the PDF
Safari hangs on the request to the 302 endpoint, the browser immediately drops the connection.

It seems that Safari does not allow `embed` or `object` elements to accept a redirect as a src/data value. It did not make a difference using 302 0r 301 redirect. I've raised the issue here because using an iframe to load the redirect works in Safari. It might be worth considering an option to fallback to an iframe for Safari.

**Comment by pipwerks** [comment]
Sorry for the delayed response. That's an interesting use case. Before I can adopt your suggested modifications, I need to ensure the existing code still runs as expected in the latest MS Edge and Firefox browsers. Edge is now using Chromium which will likely impact browser detection/handling.

**Comment by johnhunter** [comment]
Hey, no problem. Works as expected for me on Firefox and Chromium Edge (I don't think I've checked on old Edge) but I appreciate you'll want to verify.

**Comment by pipwerks** [comment]
Merged PR
