### ISSUE TITLE
Target element class "pdfobject-container" is appended on each PDFObject.embed call

### ISSUE THREAD

**Issue by johnhunter** [pipwerks/PDFObject#198]

**Comment by pipwerks** [comment]
Good catch, and you're right about implementing `classList` since we're no longer concerned about supporting IE9. If you submit a pull request with these changes I will be happy to merge. Thanks.

**Comment by johnhunter** [comment]
There's a commit in https://github.com/pipwerks/PDFObject/pull/197 (not ideal I know). I can cherry-pick it and raise a separate PR.

**Comment by pipwerks** [comment]
Merged
