### ISSUE TITLE
PDFObject embed element and Content Security Policy

### ISSUE THREAD

**Issue by jvanoostveen** [pipwerks/PDFObject#200]
On our website we have set the Content Security Policy (CSP) to not allow inline styles. This triggers an error (in the console) with PDFObject when displaying a PDF.
```
Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-VrOUUxpOhLFBWzLBigtC3NQ/UXMWqyi70ioSCXfqdHg='), or a nonce ('nonce-...') is required to enable inline execution.
```
We also have the values it sets in our css, so we actually don't need it. It would be greet if we can remove the error by either disabling the inline styles in PDFObject or maybe by changing the way PDFObject applies the styles (setting the values via JavaScript is allowed).

**Comment by zmarwa** [comment]
Any solution please!

**Comment by slav0nic** [comment]
it server-side feature, so PDFObject/browser/client-side can't do anything about it
https://content-security-policy.com/
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy

so, server should return something like:
```
Content-Security-Policy: object-src http://serevername
```
in headers
also, looks like Firefox still works fine without it, Chrome - required

**Comment by pipwerks** [comment]
Sorry for the delayed response. Inline styles are a very common part of the www... I'm not sure what the alternative is, as it doesn't make sense to create a separate stylesheet for such a small amount of CSS. 

If I understand your request, it sounds like you'd like to be able to set an option to exclude inline styles. This is do-able, but it would rely on you to properly handle the CSS on your end. I will look into it.

**Comment by pipwerks** [comment]
Updated for v 2.2.0, please see test cases at https://pdfobject.com/dev/, specifically https://pdfobject.com/dev/tests/omit-inline-styles.html
