### ISSUE TITLE
PDFObject.supportsPDFs Doesn't Support Edge Browser

### ISSUE THREAD

**Issue by theWebKeyGuy** [pipwerks/PDFObject#203]
Was attempting to use this when I ran into some issues with the browser support checker. When I attempted to use PDFObject.supportsPDFs in edge it basically gives me saying the browser doesn't support it in the console.

**Comment by pipwerks** [comment]
Apologies for the delayed response, I have not been receiving notifications for some reason.

Microsoft fundamentally changed Edge's internals -- they dropped support for their own longstanding Trident platform in favor of a Chromium fork. I have not tested PDFObject with this latest version of Edge but will try to get to it soon.

**Comment by johnhunter** [comment]
@theWebKeyGuy What version of Edge are you having problems with?

I have been unable to reproduce the issue you raised with `Version 81.0.416.64 (Official build) (64-bit)`.
- [x] Detection example: https://pdfobject.com/examples/detection.html
- [x] Embedded example: https://pdfobject.com/

**Comment by pipwerks** [comment]
I have not been able to reproduce this error. I'm happy to reopen if you provide more information. Thanks
