### ISSUE TITLE
How to add click listener?

### ISSUE THREAD

**Issue by zeejay09** [pipwerks/PDFObject#204]
I have been using this for 3 years now but suddenly my client wants to track how many people clicked the download button or print button on every PDF in my website. How can I achieve this? How can I add a click listener to the embedded pdf viewer's download and print button.

**Comment by pipwerks** [comment]
Apologies for the delayed response, I have not been receiving notifications for some reason.

PDFObject cannot access the internals of a PDF. Most PDF rendering systems do not support adding click events within a PDF, and it's pretty much impossible to implement consistently across all browsers/platforms. The one solution I can recommend is forcing the PDFs to load via PDFjs, which renders the PDF as HTML. You would have the opportunity to modify the code as needed, though I can't vouch for how easy it would be. Please note PDFjs and PDFObject are independent project and are NOT related.
