### ISSUE TITLE
pdfobject is incompatible with jest tests

### ISSUE THREAD

**Issue by jmstrick93** [pipwerks/PDFObject#205]
When trying to test React components that contain pdfobject using Jest, the component fails to render due to a null pointer exception [on this line](https://github.com/pipwerks/PDFObject/blob/883d9968fad3cefb61b1f883a81be1b5811e4113/pdfobject.js#L42) .  `navigator.mimeTypes` should be made nullsafe so that the library is compatible with Jest.  [There is already a PR up for this](https://github.com/pipwerks/PDFObject/pull/202) that I have confirmed fixes the issue on my end when running locally, but I wanted to call attention to it and elaborate on the severity of the problem it is trying to solve.

**Comment by pipwerks** [comment]
Thank you, I have merged the pull request

**Comment by alexssandrog** [comment]
Hello @pipwerks , this correction was not applied to the npm package, can do it?

**Comment by devzsolt** [comment]
> Hello @pipwerks , this correction was not applied to the npm package, can do it?

Here is the workaround meanwhile @pipwerks releases an update on npm: https://www.npmjs.com/package/pdfobject-jest

**Comment by pipwerks** [comment]
Sorry. I haven't released yet because I haven't had proper time to test across platforms. (Anyone care to help test?) And because 2020 is sucking the souls out of our bodies 😄😭

There are some minor edits that need to be made to address a couple of other issues as well.

**Comment by pipwerks** [comment]
Hello. FYI I am almost done with 2.2.0, which include a number of fixes, some refactoring, and a few new options. See commits in dev branch and test cases at https://pdfobject.com/dev/

2.2.0 will be released to NPM as soon as I can finish testing, hopefully this week. If you have some time, please kick the tires and let me know if you run into any issues. Thanks
