### ISSUE TITLE
Disable Toolbar on Firefox not working

### ISSUE THREAD

**Issue by MasterJuan** [pipwerks/PDFObject#215]
Hi,
I am using your library with these parameters:
```
var options = {
     pdfOpenParams: { toolbar: '0', statusbar: '0', messages: '0', navpanes: '0' }
};
```
It works fine on Chrome but on Firefox it still shows the toolbar.
There is any solution?

**Comment by pipwerks** [comment]
pdfOpenParam controls vary by browser, there's no universal standard. Firefox uses PDF.js to render PDFs, and according to PDF.js docs, toolbar is not a supported option. https://github.com/mozilla/pdf.js/wiki/Viewer-options
