### ISSUE TITLE
PDF.js fallback doesn't work on Chrome Browser from Android Mobile

### ISSUE THREAD

**Issue by MasterJuan** [pipwerks/PDFObject#216]
Hi again, it seems that PDF.js fallback doesn't work anymore as it supposed to be.
On Google Chrome from Android phone it shows a CTA in order to download the PDF instead of using the fallback of PDF.js. Thus, I used the forced option in the parameters.

**Comment by pipwerks** [comment]
Sorry for the delayed response.  Thanks for the report. I am testing across systems via BrowserStack and will post when I have more info. Thanks

**Comment by pipwerks** [comment]
Updated for v 2.2.0, please see test cases at https://pdfobject.com/dev/

**Comment by MasterJuan** [comment]
Thank you @pipwerks 
I will give a try!
