### ISSUE TITLE
Fallback does not work on Miui browser

### ISSUE THREAD

**Issue by snjkg** [pipwerks/PDFObject#218]
On Miui browser, which is available on the google play store and is the default browser on Xiaomi phones, no embedded PDF is displayed and also no fallback.

User agent:
Mozilla/5.0 (Linux; U; Android 9; en-gb; Mi 9T Build/PKQ1.190302.001) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/71.0.3578.141 Mobile Safari/537.36 XiaoMi/MiuiBrowser/12.2.6-g

**Comment by pipwerks** [comment]
Thank you, I will look into this. Sorry for the delayed response.

**Comment by pipwerks** [comment]
Updated for v 2.2.0, please see test cases at https://pdfobject.com/dev/
