### ISSUE TITLE
generatePDFJSMarkup

### ISSUE THREAD

**Issue by trigonal-mike** [pipwerks/PDFObject#222]
https://github.com/pipwerks/PDFObject/blob/2050e927ebea4514f0d8cfe56e9ab4f1ee13f143/pdfobject.js#L205
shouldn`t there be a "+="

greetings, mike

THX for your nice work!

**Comment by pipwerks** [comment]
Facepalm. Good catch, thanks

**Comment by pipwerks** [comment]
Actually, it should be `iframe.style.cssText`.

**Comment by pipwerks** [comment]
Fixed. What a pain, a whole new release over a single typo. Thanks for spotting it.

**Comment by trigonal-mike** [comment]
that was fast, thank you!
