### ISSUE TITLE
default height/width broken

### ISSUE THREAD

**Issue by samueltc** [pipwerks/PDFObject#223]
Hi,

Last release[1] broke the default height/width at 100%, it's now 300px by 150px.

As a workaround I had to pass ```{id: "pdfobject-container"}``` to PDFObject options and set width/height to 100% in css.

Sam 

[1] https://pdfobject.com/js/pdfobject.min.js

**Comment by pipwerks** [comment]
Hi Sam. Did you use 2.2.1? 2.2.0 had a typo regarding default iframe sizing.

Can you provide a link to an example or provide context about your embed?

Thanks

**Comment by pipwerks** [comment]
None of the test/example files on pdfobject.com exhibit any issues with regard to sizing. Please let me know if 2.2.1 resolved your issue.

**Comment by samueltc** [comment]
Yes, I switched to 2.2.1 and it resolved the issue.

Thanks!

**Comment by pipwerks** [comment]
No problem thanks for reporting and following up
