### ISSUE TITLE
Is there an es module for PDFObject???

### ISSUE THREAD

**Issue by Charles-Chiakwa** [pipwerks/PDFObject#224]
Hi,

I can't use PDFObject with es-dev-server

**Comment by pipwerks** [comment]
No, there is no es module.

**Comment by Charles-Chiakwa** [comment]
Okay, do you have any plan for this?

**Comment by pipwerks** [comment]
No, I don't currently have a use for PDFObject in ES modules. But you're welcome to contribute via a PR
