### ISSUE TITLE
embedError throws ReferenceError due to missing 2nd argument

### ISSUE THREAD

**Issue by johnhunter** [pipwerks/PDFObject#225]
Version 2.2.1

`embedError` is correctly called with the `suppressConsole` option as its 2nd argument. However the function itself does not declare the 2nd argument.

https://github.com/pipwerks/PDFObject/blob/master/pdfobject.js#L143-L148

```
let embedError = function (msg){
  ...
```
 should be 
```
let embedError = function (msg, suppressConsole){
  ...
```

**Comment by johnhunter** [comment]
We have Jest tests that would normally output "This browser does not support embedded PDFs" to the console.

But with version 2.2.1 they throw and error `ReferenceError: suppressConsole is not defined`.

**Comment by pipwerks** [comment]
Doh. PR merged. Thanks

**Comment by pipwerks** [comment]
Published

**Comment by johnhunter** [comment]
Thanks 👍
