### ISSUE TITLE
Build error line 31

### ISSUE THREAD

**Issue by luxer066** [pipwerks/PDFObject#228]
Hi PDFObject team! Thanks for your job

I found an error when performing  build.

"Build error occurred
ReferenceError: window is not defined "
Line 31

I solved it with: 
 if(!(typeof window !== "undefined") || ...

 if(!(typeof window !== "undefined") || window === undefined || 
        window.navigator === undefined || 
        window.navigator.userAgent === undefined || 
        window.navigator.mimeTypes === undefined){ 
            return false;
    }

React: 16.13.1
Nextjs: 9.5.3
PDFObject: 2.2.3

**Comment by pipwerks** [comment]
I was afraid that might happen -- I had purposely dropped `typeof` in 2.2.2+.  

Thanks for reporting, I have reverted the check back to `typeof`. It should work now (2.2.4).
