### ISSUE TITLE
Zoom doesn't work on base64 pdfs

### ISSUE THREAD

**Issue by rjtubera** [pipwerks/PDFObject#235]
Hi

I cannot make the zoom work for my base64 pdfs is this a known issue? Is there a workaround for this?

Thanks

**Comment by pipwerks** [comment]
I'm not aware of any known issues for this. To test if PDFObject is causing it (as opposed to being a browser issue), try embedding your blob using pure HTML markup with the appropriate querystring. If it doesn't work with pure HTML, it won't work with PDFObject, either. You can use the code generator on pdfobject.com to quickly put together your static HTML markup. https://pdfobject.com/generator/ (choose 'no javascript')
