### ISSUE TITLE
Allowfullscreen for Iframes

### ISSUE THREAD

**Issue by SoftCreatR** [pipwerks/PDFObject#236]
Iframes (especially those for pdf.js) should include allowfullscreen. Presentation mode isn't available on Mobile devices, if this property isn't set.

**Comment by pipwerks** [comment]
This will be added in the next update. Thanks

**Comment by pipwerks** [comment]
Forgot to include in last update. D'oh.

**Comment by pipwerks** [comment]
Actually allow=fullscreen was implemented in 2.2.5, I just forgot to denote it here. Sorry for the confusion.
