### ISSUE TITLE
Add support for external tools

### ISSUE THREAD

**Issue by SoftCreatR** [pipwerks/PDFObject#237]
Google Docs PDF Viewer 

```
https://docs.google.com/viewer?url={url}/&embedded=true
```

Adobe Embed API: https://www.adobe.io/apis/documentcloud/dcsdk/pdf-embed.html

**Comment by pipwerks** [comment]
Please provide more details and use cases.

**Comment by pipwerks** [comment]
This is an interesting concept, but I will not be taking any action without more details and use cases. I do not want to add dependencies to 3rd party services.

**Comment by pipwerks** [comment]
For the record, Google Drive's viewer will not allow itself to be embedded in other webpages, so it can't be used as a 1:1 substitute for PDFObject. 

Similarly, the Adobe Embed API requires an API key, and requires quite a bit of HTML. It's not a drop-in replacement for PDFObject.

I'm updating the PDFObject examples to include how Google's viewer can be used as a custom fallback via the `fallbackLink` option.
