### ISSUE TITLE
Base64 not working in conjunction with forcePDFJS

### ISSUE THREAD

**Issue by mrgingles** [pipwerks/PDFObject#239]
Hi,
I'm trying to show a base64 PDF using `forcePDFJS`, but it is not working. I tried using the [base64 data from your example](https://pdfobject.com/examples/base64.html) without success.

The pdf is correctly rendered if passed as URL (without base64).

**Comment by pipwerks** [comment]
Base64 has same-domain restrictions. You can only load base64 PDFs from the same domain. First thing I'd check is whether you're running into a cross-domain issue.

As for PDFJS, PDFObject merely passes the URL to PDFJS. YOu may want to look at PDFJS forums to see if anyone has issues loading Base64 PDFs in PDFJS.
