### ISSUE TITLE
navigator.mimeTypes is now deprecated in Chrome

### ISSUE THREAD

**Issue by MrSwitch** [pipwerks/PDFObject#242]
`navigator.mimeTypes` is now [deprecated](https://developer.mozilla.org/en-US/docs/Web/API/NavigatorPlugins/mimeTypes) in Chrome (as with FF)

So the following feature detection of this library is now unreliable:

https://github.com/pipwerks/PDFObject/blob/3bce0829719848a29919d605ce4cfdeb7f317ae3/pdfobject.js#L61

It is being removed from Chrome 90 (current beta) because it's considered a means of fingerprinting https://www.chromestatus.com/feature/5741884322349056.

Here's output of Chrome Version 90.0.4430.30 (Official Build) beta (x86_64) when visiting [test page](https://pdfobject.com/examples/detection.html)

![Screen Shot 2021-03-19 at 10 41 00](https://user-images.githubusercontent.com/947163/111768283-a9825280-889f-11eb-85de-5cd777325b62.png)

**Comment by pipwerks** [comment]
Thank you, an update will be posted shortly.
