### ISSUE TITLE
Pdf object and angular : compiler warning

### ISSUE THREAD

**Issue by rekna1** [pipwerks/PDFObject#244]
When using pdfobject in angular, how can I properly import pdfobject ? Does pdfobject support ECMAScript modules style? 
I tried several syntaxes of import but keep getting compiler warning:

> Angular warning states: Depending on CommonJS modules can prevent bundlers and minifiers from optimizing your application
> It is recommended that you use ECMAScript modules in your entire application.

**Comment by pipwerks** [comment]
Hi @rekna1 

PDFObject is designed to be used as vanilla JS on any webpage. The CommonJS format allows this standalone code to also be used as a package.
