### ISSUE TITLE
pdfobjectversion() - outdated version number is returned

### ISSUE THREAD

**Issue by AndreEckner** [pipwerks/PDFObject#247]
The Method pdfobjectversion() in .js and .min.js still returns "2.2.3", although version has been updatet to 2.2.5.

**Comment by pipwerks** [comment]
Oops. Thanks for the catch, will fix shortly.

**Comment by pipwerks** [comment]
PDFObject 2.2.6 is live and includes a patch for this issue. Thanks for reporting, please let me know if you run into any problems.
