### ISSUE TITLE
[Documentation] Setup using yarn (or NPM) unclear

### ISSUE THREAD

**Issue by cmahnke** [pipwerks/PDFObject#249]
As far as I understand it, PDFObject needs PDF.js to work on mobile browsers, as those doens't have a way to display PDF natively. To use PDF.js a file named `viewer.html` need to be referenced.

If one tries to use the `pdfjs-dist` package to provide `viewer.html` this file isn't part of the package.

Since I assume that nowadays many people use `yarn` or `npm` for dependency management there should be some easy instructions how to get PDFObject working on mobile devices. Or provide `viewer.html` as part of this package.

**Comment by pipwerks** [comment]
Hi @cmahnke 

PDFObject is not a rendering engine, and does not enable PDF rendering in any browser, whether desktop or mobile. PDFObject simply detects whether PDF rendering is **already supported** by the browser. If yes, it writes the necessary markup to display a PDF. If no, it provides the ability to display fallback content or perform conditional logic. 

PDFObject does not give browsers the ability to render PDFs if they do not natively support PDF rendering. Mobile browsers do not natively render PDFs (the few that do, do so incorrectly, and should not be trusted).

Therefore, PDFObject works as expected on mobile browsers.

_The inability to embed PDFs on mobile_ is beyond the scope of PDFObject, but I have presented a solution by offering integration with PDF.js, a 3rd party library. It's up to developers like yourself to decide whether you want to use PDF.js, and deal with the corresponding packaging. I will not be bundling any parts of PDF.js in PDFObject.

Good luck

**Comment by israelfloresdga** [comment]
Not about mobile browser, but I have the same question. the package does not contain viewer.html. Can you provide that file, at least as part of the documentation

**Comment by israelfloresdga** [comment]
¿How did you resolve this @cmahnke?

**Comment by pipwerks** [comment]
viewer.html is not a part of PDFObject. It's part of PDF.js, which is a completely separate project, and has its own documentation.
