### ISSUE TITLE
Your detection fails if PDF.js is added to Firefox for Android using an Add-on

### ISSUE THREAD

**Issue by M-Reimer** [pipwerks/PDFObject#250]
I'm the author of the following Add-on:

https://addons.mozilla.org/android/addon/android-pdf-js/

It is tricky to install as Mozilla doesn't like to allow every developer to create nice stuff for the "regular" Firefox, but my Add-on runs well in the "Firefox Nightly" version on Android.

On pages, which just embed PDF without any fancy JavaScript in front if it, embedded PDF works on Android with my Add-on. But as you seem to detect based on the user agent, your test cases say that there is no embed support while there, for sure, is.

Workaround: If I open your testcases in "desktop mode" on Android, then your check lets my browser pass and embeds work.

**Comment by pipwerks** [comment]
Hi @M-Reimer 

As stated in the docs, detection is essentially disabled for mobile devices. This is because none of the popular mobile OSs natively support PDF rendering (or do it incorrectly), and browsers do not provide a reliable way to test for PDF embed support (anti-fingerprinting policies led to removal of `navigator.plugins` and mime-support sniffing). PDF.js does not expose itself, either.

**Comment by M-Reimer** [comment]
Maybe nowadays it would be best to just embed PDF using an <iframe> anyway. If embedding fails, then the PDF is just offered for download.

In theory I could add support for navigator.mimeTypes to my Add-on (as it already is pretty easy to detect my Add-on anyway, this wouldn't make a too big difference) but probably it is not worth the effort.

**Comment by pipwerks** [comment]
In theory, it would be great to use an iframe everywhere and allow the browser to offer a download when embedding is unsupported. But mobile browsers are a strange world, and for some unknown reason, PDF support is missing, and there is no sane fallback. Safari in iOS will render the first page of a PDF as an image, typically scaled incorrectly, and without any proper controls. So if I were to refactor PDFObject to just use an iframe on mobile, without any detection or conditional code, PDFs on iOS would embed incorrectly and not be offered for download. Android is not any better. Hence the decision to treat all mobile devices as PDF-unfriendly by default.
