### ISSUE TITLE
Implementing PDFObject

### ISSUE THREAD

**Issue by craigbass76** [pipwerks/PDFObject#251]
I may have missed it, but don't see anything in the readme about how to go about implementing this. I know html and PHP, but not enough javascript to even be dangerous.

**Comment by pipwerks** [comment]
PDFObject.com has an example as the first item on the page.

there are also many examples you can copy. https://pdfobject.com/#examples

**Comment by craigbass76** [comment]
Doh! I didn't see the pdfobject.com link. As I implied though, I tend to miss things when they're right in front of me. Thanks!

**Comment by pipwerks** [comment]
No worries. It's a good reminder for me to make it more obvious in the readme.

**Comment by pipwerks** [comment]
readme has been updated to specifically call out pdfobject.com. Thanks
