### ISSUE TITLE
How to get the currently page?

### ISSUE THREAD

**Issue by HD3699** [pipwerks/PDFObject#252]
want to load to the last read location, can set the page of options to jump to the specified location, but how to remember which page is currently read?
想要做一个加载到上一次阅读位置的功能，可以通过options设置page跳转到指定位置，但是如何记下当前读到了哪一页呢？

**Comment by pipwerks** [comment]
Unfortunately there is no standard JavaScript API for PDF viewer apps and no way to get the page number. The only solution I can think of is to use PDF.js (unrelated to PDFObject). PDF.js uses JavaScript to render the PDF, and provides much more control than native PDF viewers. Good luck.

**Comment by HD3699** [comment]
toolbar of pdfOpenParams is open, then it will show a page and total, can I get it from this?

**Comment by pipwerks** [comment]
No, because JavaScript does not have access to the PDF toolbar.
