### ISSUE TITLE
pdf view is doubled/bad text rendering when High Contrast is enabled

### ISSUE THREAD

**Issue by aravindSiruvuru05** [pipwerks/PDFObject#253]
the PDF loaded in high-contrast mode in windows is displacing the content and making the UI not readable.

attached the images:
![image](https://user-images.githubusercontent.com/64730187/129144170-6168f184-41b8-4566-9886-a8f4221dc50e.png)

![image](https://user-images.githubusercontent.com/64730187/129143980-db92266d-0b27-4d71-a643-1160c55e81fe.png)

**Comment by pipwerks** [comment]
The rendering of the PDF is not handled by PDFObject. Please check the documentation at https://pdfobject.com which describes PDFObject's features and functions.

**Comment by aravindSiruvuru05** [comment]
it would be better if it give an option to disable the top text rendering

**Comment by pipwerks** [comment]
This is completely unrelated to PDFObject
