### ISSUE TITLE
PDF docs on several tabs: same tab won't work twice

### ISSUE THREAD

**Issue by bmann22222** [pipwerks/PDFObject#254]
Hello,
I have a page that displays separate pdf's on several tabs. When I first click on a tab, it displays the pdf properly. However, if I click on another tab (displays properly), then click again on the original tab, the pdf will not display. I cannot view that pdf again until I refresh the page. I am using PDFObject.embed in js using a link in the tab. Currently running version 2.0.20171219. Is this a known issue, perhaps has been resolved in a more recent version? Thanks.

Update: I just discovered that the document is, in fact, there, but you need to scroll to the bottom of the panel in order for it to display!

**Comment by pipwerks** [comment]
It sounds like you might have a CSS issue.

And yes, you definitely want to use the latest edition of PDFObject, it has a number of improvements and bug fixes.

Good luck
