### ISSUE TITLE
Present Not working

### ISSUE THREAD

**Issue by eMerzh** [pipwerks/PDFObject#255]
Hello 👋 
thanks for your  useful project :)

i was trying to implement it, but i noticed that the "present" option didn't worked in chrome

I suspect something related to iframes or something. Unsure if chrome bug or if it's the embedding technic 

the https://pdfobject.com/ homepage suffer from it as well...

<img width="837" alt="image" src="https://user-images.githubusercontent.com/177003/129599151-29e39ac8-b6a9-47e0-bd2c-98cb169b4f70.png">

Version 92.0.4515.131 (Official Build) (x86_64) on OSX

**Comment by pipwerks** [comment]
Hello

Unfortunately, PDFObject does not have any control over features and toolbar options provided by the various PDF rendering engines (Chrome, Firefox, Edge, Acrobat, Preview, PDF.js, etc.)

https://pdfobject.com/#the-why  

Chrome's "Present" function doesn't work for me in most situations, and it doesn't seem to matter whether the PDF is embedded as an `<embed>` or `<iframe>`.

If anyone has any info/insight about Chrome's presentation mode requirements, please let me know.

**Comment by theodore-s-beers** [comment]
Presentation mode is meant as a full-screen view. I wouldn't expect it to work when starting from an `<embed>` or `<iframe>`. The quirk here is that Chrome shows the normal toolbar for an embedded PDF, just as if it were a PDF opened in a tab of its own. So you'll see a (probably) nonfunctional option for presentation mode. (Everything else in the toolbar should work as expected.)

**Comment by eMerzh** [comment]
Thanks guys .. after looking this up more, it seems to be a chrome bug ... so i guess we can close this 🤔
