### ISSUE TITLE
PDF not displaying on Android.

### ISSUE THREAD

**Issue by typevitor** [pipwerks/PDFObject#256]
Hello. 

I'm using PDFObject v 2.3.3 in a Laravel + Vuejs project, and I'm having issues displaying the embed PDF on android devices. It displays a black screen with the blob and a button with the label "open" that does nothing. The blob is correctly being loaded as when the fallback URL is displayed, the user can download the document. The fallback URL is **NOT** being rendered on Android. It works fine on iOS devices.

![img](https://user-images.githubusercontent.com/4871162/130961187-7f6617ce-bab2-4ec4-8eda-b9b76ea5eb77.png)

Already tried upgrading to the latest version, didn't work out.

**Comment by pipwerks** [comment]
You have `forcePDFJS` set to true. That means you need to provide a PDFJS viewer. Are you using PDFJS? 

If you're not using PDFJS, set `forcePDFJS` to false or remove that line from your options object.

If you *are* using PDFJS, I would try embedding the PDF without PDFJS (set `forcePDFJS` to false). If the embed/fallback works without PDFJS, it's likely PDFJS is causing the issue. You'd need to go to PDFJS forums for further guidance, as that's a separate utility and not part of PDFObject.

**Comment by typevitor** [comment]
Setting forcePDFJS to false made the fallback url work. Thank you!
