### ISSUE TITLE
Title attribute does not work for iframe

### ISSUE THREAD

**Issue by Rathe001** [pipwerks/PDFObject#258]
As per #248 a title attribute should be added to both the `embed` and `iframe` tags.  `embed` is working fine, but `iframe` still lacks a title attribute. We are using forcePDFJS: true, so in our case the `iframe` is always used.

**Comment by theodore-s-beers** [comment]
The problem isn't with iframe per se; it's with `forcePDFJS`. That ends up calling a different function, `generatePDFJSMarkup`, which still doesn't incorporate the title argument. But it should be an easy fix.

**Comment by pipwerks** [comment]
Oops. Good catch, will fix soon.

**Comment by pipwerks** [comment]
Fixed. Thanks for the heads up.
