### ISSUE TITLE
fallbackLink can't evaluate to false

### ISSUE THREAD

**Issue by theodore-s-beers** [pipwerks/PDFObject#264]
`fallbackLink` can be set as a string or as a Boolean. But if it's set to false, it will be overridden to true by this line:

```js
let fallbackLink = opt.fallbackLink || true;
```

([link to line](https://github.com/pipwerks/PDFObject/blob/61d6ddb7ce6165226ccb8415c637066e949a6fc3/pdfobject.js#L274))

I'll open a PR to fix this shortly. I see that the same issue has already been handled for other Boolean properties.

**Comment by pipwerks** [comment]
Good catch, let me test the code before merging. Thanks

**Comment by theodore-s-beers** [comment]
Yeah. With the change made, I checked the following:

- `fallbackLink` not set (defaults to true, as expected)
- set to false (no fallback, as expected)
- set to true (default fallback, as expected)
- set to empty string (subsequently evaluates to false, which seems right)
- set to non-empty string (this becomes the new fallback message, as expected)

But there could be other cases I didn't think of.

**Comment by pipwerks** [comment]
Haven't forgotten about this, just been very busy...

**Comment by theodore-s-beers** [comment]
Not urgent. I don't use this parameter. I just noticed while converting (a simplified version of) PDFObject to TypeScript, that the type of `fallbackLink` was being inferred as `true`.

**Comment by pipwerks** [comment]
Fixed in 2.2.8, available for testing in a new branch https://github.com/pipwerks/PDFObject/tree/2.2.8

I have tested locally and via BrowserStack, I will merge w Master after I test a little more.
