### ISSUE TITLE
pdfOpenParams with toolbar

### ISSUE THREAD

**Issue by alainrc2005** [pipwerks/PDFObject#272]
In version 2.2.7 this work
{ pdfOpenParams: { toolbar: '0' } }
but in version 2.2.8 this not work

**Comment by theodore-s-beers** [comment]
@pipwerks, I think this is actually a bug. As of the 2.2.8 updates/refactor (commit e72762d), `pdfOpenParams` isn't being included at all, except when PDF.js is used.

**Comment by pipwerks** [comment]
Thanks both. I will check it out

**Comment by pipwerks** [comment]
Fixed in 2.2.9 branch, needs testing before I can publish to NPM. Will try to test asap

**Comment by alainrc2005** [comment]
Thanks Very Much

**Comment by pipwerks** [comment]
Hi all. I've behind on testing, been busy with work and other projects. I'm curious if anyone has tested the 2.2.9 branch. I will try and wrap it up this weekend, would be great if others can share any testing results.

**Comment by pipwerks** [comment]
Resolved with 2.2.9 release
