### ISSUE TITLE
Optional lazy loading of iframes

### ISSUE THREAD

**Issue by SoftCreatR** [pipwerks/PDFObject#274]
It would be nice, if we could optionally set the `loading`-attribute to generated iframes for lazy loading.

See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe?retiredLocale=de#attr-loading

**Comment by SoftCreatR** [comment]
But there's no downside, when implementing it, even if not all Browsers support it yet.

**Comment by pipwerks** [comment]
Actually, there's quite a bit of downside, including:

* potential issues if the final implementation of `loading` varies from the current version
* potential issues if the various browsers don't support the feature in the same way (e.g. use different syntax)
* support issues from people asking why it doesn't work in *x* browser, not knowing that the feature isn't supported there yet (much like how people wonder why most Open PDF Params won't work when they don't have Adobe Reader)

And so on. I've been around long enough to have been bitten by this before, I will wait until the feature is more mature. But it's good to see this feature is in the works. Thanks for the suggestion.

**Comment by SoftCreatR** [comment]
That's why I've suggested to make this optional ;) Alternatively, you could just add the possibility for developers to add custom properties to the generated iframes.

**Comment by theodore-s-beers** [comment]
> Alternatively, you could just add the possibility for developers to add custom properties to the generated iframes.

This might be worth thinking about. It could eventually reduce the maintainership burden on PDFObject. People ask for a new embed/iframe property, and you can tell them to feel free to pass it raw on their own.

**Comment by SoftCreatR** [comment]
That's what I thought.

**Comment by pipwerks** [comment]
I'll reopen as a feature request for ability to add attributes to the embed/iframe elements.

**Comment by pipwerks** [comment]
Resolved with 2.2.9 release
