### ISSUE TITLE
Eraser

### ISSUE THREAD

**Issue by sonakinci41** [pipwerks/PDFObject#279]
The computer I am currently using pdffoject has only a touchscreen and I can't use a keyboard. It is difficult for me to erase the writings when I wrote with pen. Is it possible to add any icon for delete function? Or is there any avaible method for that issue I mentioned? Thank you.

**Comment by pipwerks** [comment]
I'm sorry but PDFObject does not control any of that functionality. The PDF rendering engine (native apps, PDFJS, Adobe Acrobat, etc) provide the user interface buttons. It's outside the scope of PDFObject.
