### ISSUE TITLE
Use google docs PDF conversion for mobile devices?

### ISSUE THREAD

**Issue by Hogflash** [pipwerks/PDFObject#282]
Just a suggestion to add an option to use the google documents PDF conversion utility for mobile browsers that do not natively support PDFs.  This (mostly) involves generating an iframe with the appropriate URLs & parameters (e.g., src="https://docs.google.com/viewer?embedded=true&url=FILE_URL" along with some iframe parameters for sizing).  I think you have already done most of the heavy lifting to get there, this could be an optional feature.   

Thanks, Gary

**Comment by theodore-s-beers** [comment]
Very interesting! It does seem to work. Here's a minimal example:

https://gdocs-pdf-embed.pages.dev/

I used the following HTML:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>PDF embed via Google Docs</title>
  </head>
  <body style="max-width: 72rem; margin: 0 auto; padding: 1rem">
    <iframe
      width="100%"
      height="500px"
      src="https://docs.google.com/viewer?embedded=true&url=https://pdfobject.com/pdf/sample-3pp.pdf"
    ></iframe>
  </body>
</html>
```

**Comment by pipwerks** [comment]
It's an interesting idea, but using this technique will cause Google to scan and cache your file. Many companies who use PDFObject use it for proprietary documents (financial, legal documents, technical), which they'd prefer not to give to Google. 

Also FWIW there are other providers who provide a similar PDF preview service, like Microsoft. https://gist.github.com/tzmartin/1cf85dc3d975f94cfddc04bc0dd399be

**Comment by theodore-s-beers** [comment]
Yeah, I can't imagine having such a thing enabled by default in a FOSS PDF embedding library. Even having it on an opt-in basis would probably raise some eyebrows.

**Comment by Hogflash** [comment]
I would definitely NOT make this an automatic fallback - It would have to
be explicitly enabled.  I agree that once sent to Google, it is now
"public" information.  In many cases that is not acceptable, but for some
sites it is not an issue.  But, there is always the possibility of someone
not understanding this and assuming it is private.

**Comment by theodore-s-beers** [comment]
I added a rough implementation of this to [my fork](https://github.com/theodore-s-beers/pdfo). You can see it in action [here](https://www.theobeers.com/kwd-reader/). A few notes, in case they might be useful to someone down the line:

Basically, I added a new member, `fallbackPrefix`, to the options that can be passed to the `embed` function. The prefix could be e.g. `https://docs.google.com/viewer?embedded=true&url=`.

If `fallbackPrefix` is set, it supersedes `fallbackLink`:

```ts
const fallbackPrefix = opt.fallbackPrefix || ''
const fallbackLink = fallbackPrefix
  ? false
  : typeof opt.fallbackLink === 'string' ||
      typeof opt.fallbackLink === 'boolean'
    ? opt.fallbackLink
    : true
```

Then `embed` can call the markup generation function, with `fallbackPrefix` prepended to the `url`:

```ts
if (fallbackPrefix) {
  const embedType = 'fallback'

  return generatePDFoMarkup(
    embedType,
    targetNode,
    targetSelector,
    fallbackPrefix + url,
    pdfOpenFragment,
    width,
    height,
    id,
    title,
    omitInlineStyles
  )
}
```

Finally, when generating markup, we just have to make sure to create an iframe with the correct `src` attribute:

```ts
if (embedType === 'iframe' || embedType === 'fallback') {
  embed = document.createElement('iframe')
  embed.allow = 'fullscreen'
} else {
  embed = document.createElement('embed')
  embed.type = 'application/pdf'
}

embed.src = embedType === 'fallback' ? url : url + pdfOpenFragment
```
