### ISSUE TITLE
[Documentation] Standalone examples of .html files + PDFObject?

### ISSUE THREAD

**Issue by rubyFeedback** [pipwerks/PDFObject#283]
Hello there,

I just found the project via a google search. The documentation shows how to
use it, but is there a complete example, a standalone .html file and a test
.pdf file? Something to test it with.

Right now I am not entirely certain what one can do with PDFObject, as
opposed to just using the embed tag. I am  probably missing something,
which is why I think it would be best to have some kind of demo-page
that we could download and test locally. I could, of course, read more 
and experiment on my own, but I was only searching for a short moment
and moving on to do something else (learning for an upcoming exam
next week, so I don't have that much time). Anyway, thank you for reading
this request and perhaps considering it.

**Comment by pipwerks** [comment]
> Examples and documentation can be found at https://pdfobject.com/

Good luck

**Comment by theodore-s-beers** [comment]
The site is hosted from the `gh-pages` branch of the GitHub repo. It can be convenient to go straight to the HTML files in the `examples` directory:

https://github.com/pipwerks/PDFObject/tree/gh-pages/examples

**Comment by pipwerks** [comment]
As always, great tip @theodore-s-beers Thanks
