### ISSUE TITLE
Remove some buttons and only show one page at a time

### ISSUE THREAD

**Issue by Boy19991** [pipwerks/PDFObject#284]
Greetings,

May I ask is it possible to remove most buttons from the toolbar, especially download, and then only show one page at a time, letting the user navigate from there?

Best regards, Jolly Boy

**Comment by pipwerks** [comment]
Sorry, toolbars are controlled by the PDF rendering app, and cannot be controlled by PDFObject. There is no standard API for controlling toolbars. You may be able to achieve your goal with a modified version of [PDF.js](https://github.com/mozilla/pdf.js). Good luck
