### ISSUE TITLE
Is there a way to track button clicks?

### ISSUE THREAD

**Issue by andrisole92** [pipwerks/PDFObject#289]
E.g. I want to know when and how people click download button or any other buttons?

**Comment by pipwerks** [comment]
No, PDFObject simply embeds the file into the HTML page. PDF rendering engines don't provide an API for tasks like click tracking. You'd have to build your own by modding PDF.js or similar.

**Comment by knubew** [comment]
Basically, you could use the click event for the button that calls up the PDF. Then you can at least track who called up the PDF for display. At least that's how I do it in my project.

If you use jQuery in your project, have a look here: [http://api.jquery.com/click/](http://api.jquery.com/click/)

For pure vanilla script look here for example: [https://wiki.selfhtml.org/wiki/JavaScript/DOM/Event/click](https://wiki.selfhtml.org/wiki/JavaScript/DOM/Event/click)
