### ISSUE TITLE
PDFObject: Page option not working in Microsoft Edge

### ISSUE THREAD

**Issue by Rushita-Ginoya** [pipwerks/PDFObject#291]
After refreshing the page, the PDF document using PDFObject does not start from the first page, even though I have specified the option **pdfOpenParams: { page: 1 }.**

**Expected Behavior:**
When the page is refreshed, the PDF document should start from the first page.

**Steps to Reproduce:**
-     Open the following example in Microsoft Edge: https://pdfobject.com/pdf/sample-3pp.pdf
-     Scroll to the third page of the PDF document.
-     Refresh the browser.

**Observed Behaviour:**
After refreshing the page, the PDF document continues to appear from the third page instead of starting from the first page.

Additional Information:
I have tried using the pdfOpenParams option with { page: 1 } to ensure that the PDF starts from the first page. However, this does not seem to work in Microsoft Edge.

Potential Solution:
I have already attempted the following steps to resolve the issue:
-     Cleared the browser cache in Microsoft Edge.
-     Ensured that I am using the latest version of Microsoft Edge.
-     Disabled any PDF-related extensions or plugins in the browser.
-     Tested the issue in other browsers (Google Chrome, Mozilla Firefox, and Safari).

Despite these efforts, the problem persists. It would be greatly appreciated if the development team could investigate this issue and provide a solution or workaround for making the page option work correctly in Microsoft Edge.

Environment:

    Microsoft Edge version:  114.0.1823.51
    Operating System: Ubuntu, Windows

**Comment by pipwerks** [comment]
Thanks for the detailed submission. Unfortunately, this is not something PDFObject can control. This behavior will be dependent on the PDF viewer provided by the browser.

One potential workaround is to remove the embedded PDF and re-embed.

Good luck

**Comment by theodore-s-beers** [comment]
For what it's worth, I was able to reproduce this in Edge on macOS. I have a feeling that Microsoft would describe this as a feature: "the in-browser PDF viewer saves your spot!"

Also note that support for PDF Open Parameters is rather spotty—when it's supported at all.
