### ISSUE TITLE
The problem occurred when using PDFObject in React: Page A embedded with duplicate Page A. 

### ISSUE THREAD

**Issue by CSilver20** [pipwerks/PDFObject#292]
Using PDFObject in React can cause problems similar to deprecated tags <embed> and <object> in browsers (embedding duplicate single page A in single page A), and it cannot achieve the expected PDF preview.

**Comment by pipwerks** [comment]
Hi @CSilver20, I'm not sure I follow what you're saying. Can you provide an example?

PDFObject was developed for vanilla JS. React is a very different way of approaching the DOM, I would not be surprised if there are compatibility issues between React and PDFObject. Some folks have created React wrappers for PDFObject, but I can't speak to their quality or reliability.

**Comment by ukrutt** [comment]
For what it's worth, I was able to use https://github.com/sugarshin/react-pdfobject successfully.
(And thank you, @pipwerks, for creating this utility! It works amazingly well in its relative simplicity.)

**Comment by pipwerks** [comment]
Thanks @ukrutt. Closing due to lack of follow up from @CSilver20
