### ISSUE TITLE
Prevent download pdf automatically

### ISSUE THREAD

**Issue by billoneillighttiger** [pipwerks/PDFObject#294]
I have tried to embed this pdf into an HTML file and run the code, but can't see the embedded pdf, but automatically downloaded, how to prevent this? 
https://storage.procore.com/v4/d/us-east-1/pro-core.com/56ce94e3-bab3-4b0d-ad4b-da9b8c6e7214_production_merged.pdf?sig=a0c7612dd0d6a588c0b1fcac152aee6818fa926642b83fb87325c956fabe9b1e

**Comment by pipwerks** [comment]
The server needs to serve the file with the Content-Disposition header set to inline. https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition

If the server is already configured properly, double-check that your browser is configured to display PDFs inline and doesn't auto-download them. This is user-configurable and varies from browser to browser. (By default, all major browsers display PDFs inline.)
