### ISSUE TITLE
IE requests document twice

### ISSUE THREAD

**Issue by panzuriel** [pipwerks/PDFObject#3]
See http://support.microsoft.com/kb/293792

IE (6 and 8 I've tested) sends two requests for the pdf. The suggested solution:

```html
<OBJECT CLASSID="clsid:CA8A9780-280D-11CF-A24D-444553540000" STYLE="height:100%; width: 100%" >
   <PARAM NAME="src" VALUE="http://server/path/filename.pdf">
</OBJECT>
```

doesn't work in other browsers (Chrome, Firefox), so you need to do browser detection, so I've done this:

```javascript
		if (navigator.appName == 'Microsoft Internet Explorer') {
			targetNode.innerHTML = '<object	CLASSID="clsid:CA8A9780-280D-11CF-A24D-444553540000" width="' +width +'" height="' +height +'"><param name="src" value="' +url +'"></object>';
		} else {
			targetNode.innerHTML = '<object	data="' +url +'" type="application/pdf" width="' +width +'" height="' +height +'"></object>';
		}
```

**Comment by pipwerks** [comment]
Thanks, it's been a few years since this case was opened. Now that Microsoft is clearly moving away from ActiveX and proprietary code (attempting to make their latest browsers behave more like Chrome/Firefox/Webkit), I will aim to avoid any IE-specific cod where I can.
