### ISSUE TITLE
Question: Config option for Two-page view?

### ISSUE THREAD

**Issue by eirabben** [pipwerks/PDFObject#303]
I am using PDFObject to show some PDFs on a website. In the UI on Chrome, I have the option to activate Two-page view. Is there a way to activate this by default with a config option or similar?

**Comment by theodore-s-beers** [comment]
This would be via [PDF Open Parameters](https://pdfobject.com/guide/browser-support.html#pdf-open-parameters), but I'm not aware of one for two-page view.

**Comment by pipwerks** [comment]
Unfortunately, no, there is no standard option to force a 2-up view. You may be able to do it with a custom PDF.js implementation, but not with browser-native PDF rendering engines.
