### ISSUE TITLE
Embed Base64 30 MB or more dont show 

### ISSUE THREAD

**Issue by CesarMar05** [pipwerks/PDFObject#307]
I tried to embed a base64 pdf of 40 MB or more and the file dont show on the div, with files less than 30 MB its shows. 

PDF of 28 MB 

![image](https://github.com/user-attachments/assets/2ea71d90-f0d0-4723-b63b-0019c9fad457)

PDF of 40 MB

![image](https://github.com/user-attachments/assets/2ae3339c-442f-4392-a167-46588bd7863e)

This is my script, for security ressons I can´t share the txt files that contains the base64 string

[LeeArchivo.txt](https://github.com/user-attachments/files/17562032/LeeArchivo.txt)

Thanks in advance for the support.

**Comment by pipwerks** [comment]
Hi @CesarMar05 

Unfortunately, you're at the mercy of browsers to support large base64 PDFs, there's nothing PDFObject can do to change how browsers handle these files. PDFObject simply writes HTML to the page, the browser handles the PDF rendering.

If you really need to be able to display a large base64 PDF, you could try bypassing the native PDF rendering via PDFJS.

Good luck

**Comment by xhuanhuan** [comment]
pdf over 1.5M dont show

**Comment by pipwerks** [comment]
As I wrote earlier, this is not something that cannot be controlled by PDFObject.
