### ISSUE TITLE
Same origin policy in using iframe to render PDF file

### ISSUE THREAD

**Issue by TD-tenglong** [pipwerks/PDFObject#308]
If an iframe embeds a PDF document and the PDF's URL is not from the same origin as the web app's URL, will the PDF fail to render?

**Comment by pipwerks** [comment]
PDFs generally will embed regardless of what domain they're served from, similar to how an image can be embedded from any domain. However, the domain that serves the PDF and the domain that hosts the iframe each have a level of control that can disallow the embed if desired.
