### ISSUE TITLE
PDFs are rendering with edit button causing issues in the app

### ISSUE THREAD

**Issue by Jejugo** [pipwerks/PDFObject#309]
I am using PDFObject in one of my projects and I noticed some PDF files can be edited, which is causing a lot of issues in my application

![image](https://github.com/user-attachments/assets/1c261106-f885-4d2e-8c3a-801356d29177)

Does anybody else also got this? Is there a way to hide it or just embed the viewer without those options?

**Comment by pipwerks** [comment]
You could also try hiding the entire toolbar, but not all browsers respect/obey the command.

[Here is a list of PDF Open Params and associated browser support](https://pdfobject.com/guide/browser-support.html#pdf-open-parameters).
