### ISSUE TITLE
PDFObject not detecting PDF support in IE11

### ISSUE THREAD

**Issue by tommywhited** [pipwerks/PDFObject#31]
Even with the Adobe PDF addon enabled, PDFObject doesnt detect PDF support in IE11. It fails to create the activex control, and the PDF reader is not listed in the navigator.plugins or mimetypes. 

Im using IE11 on a 64bit windows 7 machine.

**Comment by pipwerks** [comment]
Thanks for the info. I know it's a bit late, but I am working on updates to fix issues with 'modern' IE and more.

**Comment by bvacchiano** [comment]
@pipwerks - I'm experiencing this problem as well. @tommywhited's solution did not work for me unfortunately.
