### ISSUE TITLE
.embed("pdf") Embed Muliple PDFs using "class="pdf"" instead of "id="pdf1"/"PDF2""

### ISSUE THREAD

**Issue by aasthatuteja** [pipwerks/PDFObject#35]
Similar to "Issue #14 - .embed("pdf");" issue, I am facing problem when try to embed multiple PDFs, I want to use multiple DIVs, but I want to use "Class" instead of different "IDs", as all DIVs will be generated at runtime. 

I have Image slider where in some cases I have to show PDF, so the 1st instance of PDF works fine but rest all I get the error message which I have added in the : div id="pdf"

I saw the JS, its fixed to use either ID or Node name. So in my case, neither I can use ID nor node name as there are many DIV in my page.

Can you please look into this ASAP and suggest how this can be fixed.

Just FYI, for slider I am using "Galleriffic plugin > http://www.twospy.com/galleriffic/", and I am putting the PDF div inside "div class="caption"" where you can show the description related to the image.

**Comment by pipwerks** [comment]
PDFObject does not need to be changed to meet this need.
