### ISSUE TITLE
Provide a cross-browser onload event

### ISSUE THREAD

**Issue by filipefigcorreia** [pipwerks/PDFObject#38]
It's hard to detect when a PDF has finished loading in such a way that works on all browsers. It would be great of PDFObject could provide such an event.

Note that, I am not sure if this is at all possible to do with current browser implementations. The absense of relevant answers to [this question on stackoverflow](http://stackoverflow.com/questions/23115763/detecting-when-a-pdf-finishes-loading-within-an-object-tag) is not encouraging.

**Comment by niklas-dahl** [comment]
ist there now 4 years later the possibility to get a load event?

**Comment by pipwerks** [comment]
This is not possible due to a limitation in the browsers themselves -- their built-in PDF rendering engines do not provide APIs. There is no 'loaded' event, and no way to know whether the PDF has properly loaded.

**Comment by cwilby** [comment]
I'm not sure if this changed recently, but it looks to be possible to add a `load` event listener to either the iframe (PDFObject 2.x) or object (PDFObject 1.x) as follows:

## v1.2.0
```js
PDFObject({ url: '/test.pdf' }).embed(document.querySelector('#pdf'));

document.querySelector('#pdf object').addEventListener('load', function () {
    alert('loaded');
});
```

## 2.3.0
```js
PDFObject.embed('/test.pdf', '#pdf');

document.querySelector('#pdf iframe').addEventListener('load', function () {
    alert('loaded');
});
```

I am currently using this to implement a loadmask/spinner.

**Comment by pipwerks** [comment]
Now that PDFObject uses iframes exclusively, the onload handler will be consistent across browsers. 

**Important:** The onload event only indicates that the iframe has loaded *something*, there is no guarantee the iframe has properly loaded the PDF (and no way to check).

```
let pdf_iframe = PDFObject.embed("myfile.pdf");
pdf_iframe.addEventListener('load', function () {
    alert('loaded');
});
```

**Comment by pipwerks** [comment]
I added this use case to the docs https://pdfobject.com/examples/#callback-on-onload-event
