### ISSUE TITLE
Byte stream as source

### ISSUE THREAD

**Issue by John--Mann** [pipwerks/PDFObject#39]
Add ability to use a byte stream as source for viewer instead of just a file on disk.

**Comment by pipwerks** [comment]
Thanks, but all PDFObject does is write the `<object>` markup in the HTML doc. Browser support for PDFs as byte streams is a browser (or plugin) issue beyond the scope of PDFObject.

**Comment by John--Mann** [comment]
Thanks for the followup. I did eventually find another solution.
John

**Comment by ashatat** [comment]
@John--Mann  can you please share with me the solution for your issue?
