### ISSUE TITLE
Add to documentation that server must support HEAD requests to work in IE9-10

### ISSUE THREAD

**Issue by fetherston-cais** [pipwerks/PDFObject#42]
Many server frameworks (such as spring) reject HEAD requests by default, causing the PDF document request to fail in IE9 and 10. Took me some time to chase this one down.

**Comment by pipwerks** [comment]
Thanks for the detailed information. To be perfectly honest, I'm not sure how to handle this, as it isn't a PDFObject code issue. I don't want to maintain documentation for something that's beyond the scope of my own work. For now I will close this, as it is not a code issue. Hopefully people who encounter the problem you describe will find this via search.
