### ISSUE TITLE
ReferenceError Filename

### ISSUE THREAD

**Issue by goatandsheep** [pipwerks/PDFObject#48]
The filename needs to be different than the variable name. For example, instead of saying `var PDFObject`, and `pdfobject.js`, try `var ObjectPDF`

**Comment by pipwerks** [comment]
This is a matter of opinion, and I do not agree. Can you explain why you're saying it needs to be different? I suspect you're using some kind of script loader that chokes on it. If this is the case, the problem lies within the script loader.

**Comment by goatandsheep** [comment]
How do I make a script loader that does not choke on it? I used your example when trying to get it to run.

**Comment by pipwerks** [comment]
By script loader I mean something like require.js or LABjs.

**Comment by goatandsheep** [comment]
Nope. I'm not using a script loader. I guess it's your choice whether or not to fix it, though.

**Comment by pipwerks** [comment]
It's not broken.
