### ISSUE TITLE
Firefox uses different mimetype [Fixed]

### ISSUE THREAD

**Issue by goatandsheep** [pipwerks/PDFObject#49]
Firefox uses [text/html] instead of [application/pdf] as a mimetype. I made [something](https://github.com/communotey/communotey.github.io/blob/master/js/pdfobject.js) that should fix this issue and the last issue I submitted.

Test compatibility [here](https://communotey.github.io/pdftest).

**Comment by pipwerks** [comment]
Thanks for the tip, I will check it out.

**Comment by pipwerks** [comment]
PS if you submit as a pull request, it makes it much easier/faster to diff the changes and see what you've done.

**Comment by goatandsheep** [comment]
Ohhh that's what that means. I'll try that. Thanks!
Also, I realized that there are a ton of bugs in my code anyways. So I won't try that until I fix the bugs.

**Comment by pipwerks** [comment]
I'm not sure where you got your information, but I just confirmed Firefox supports application/pdf, as it should. (As it has for years.)

**Comment by goatandsheep** [comment]
Checked through javascript in console and it's not in the navigation.mimeTypes array. Also double-checked using [this external checker](http://www.pinlady.net/PluginDetect/PDFReader/).

Your full screen example:
![This is what happens normally in my firefox browser](https://cloud.githubusercontent.com/assets/5570628/5618432/04890880-94e7-11e4-8bb6-f2533efd22e6.png).

Object file with `text/html` (using your scripts)
![This is what happens if I added an object at the end of the exact same file](https://cloud.githubusercontent.com/assets/5570628/5618433/048c2240-94e7-11e4-9136-22487f167987.png)

**Comment by goatandsheep** [comment]
This is covered by [this issue](https://github.com/pipwerks/PDFObject/issues/93)
