### ISSUE TITLE
False positives and false negatives

### ISSUE THREAD

**Issue by gweax** [pipwerks/PDFObject#5]
I'm both having false positives and false negatives.

- In my Opera 11.51 (Windows 7) I have the "Adobe PDF Plug-In for Firefox and Netscape '9.3.4'", but PDFs are not displayed. The fallback text within the object element however is.

- In my IE9 (Windows 7), the detection does not throw an error, a plugin is detected, but the PDF is not displayed (neither is the fallback text within the object element).

- In my IE8 (Windows XP), first a script error is thrown in both "new ActiveXObject();" lines in hasReaderActiveX, even though I have a PDF Plug-In.

I wrapped the offending lines in try..catch, but that only prevents the script error, still the detection is wrong (well, the try..catch cannot fix that of course).

**Comment by pipwerks** [comment]
Sorry for leaving this hanging for so long. Now that all the browsers (and plugins) in question are clearly outdated, I am closing this issue.
