### ISSUE TITLE
Nice effort

### ISSUE THREAD

**Issue by flik** [pipwerks/PDFObject#51]
I like your project and it is still a need of this time. I can contribute into your project. I am exploring this. 
Can you share with me a simple use with a little example ?

**Comment by jiyinyiyong** [comment]
Here's how we use this:
```coffee
loadPdf = ->
  node = @refs.root.getDOMNode()
  url = @props.data.previewUrl or @props.data.downloadUrl
  PDFObject(url: url).embed(node)
```
I suppose the author is no longer maintaining this repo...

**Comment by jtjonz** [comment]
The author has some examples and explanation on this project's site: [PDFObject.com](http://pdfobject.com/)
