### ISSUE TITLE
PDFObject fails on array of parameters

### ISSUE THREAD

**Issue by geeveebee** [pipwerks/PDFObject#52]
Hello,

I found this, well actually the outdated 1.2 on the main site, script and started inplementing it as it works more elegant on IE than my object data parameter replacement script which sometimes caused error about a .tmp pdf that could not be loaded.

Anyway...

All seemed to work fine till I bumped on an issue today.

One of my applications is sending an array of form settings to the pdf creation page.
It is being sent as data[]=value1&data[]=value2 etc.

The problem is this line

a=encodeURI(h.url)+"#"+q(g);

as it caused the query string to be data%5B%5D=value1&data%5B%5D=value2 the PHP file doesn't recognize it as an array anymore.

I had to change it to

a=h.url+"#"+q(g);

to bypass my problem.

I'm not sure if there is a more elegant method so that html enities and other codes get sent correctly aswell?

**Comment by geeveebee** [comment]
you can discard this issue :)

JQuery's .serialize already did the url encoding so you script did it a second time.

I solved my issue with

data=$("#myform").serialize().replace('%5B%5D', '[]');

**Comment by geeveebee** [comment]
just in case someone else has issues with this...

use this instead (javascript replace only replaces the first occurence so the pdf only contained 1 record)

data=decodeURI($("#myform").serialize());

**Comment by pipwerks** [comment]
Thanks for the info, I definitely need to do some updates. :/
