### ISSUE TITLE
IE11 Does not see the ActiveX object

### ISSUE THREAD

**Issue by huthwac** [pipwerks/PDFObject#54]
If you change the embed function to this

var embed = function(targetID){

		var iframe = false;
		if(!pluginTypeFound){ iframe = true; }

		var targetNode = null;

		if(targetID){

			//Allow users to pass an element OR an element's ID
			targetNode = (targetID.nodeType && targetID.nodeType === 1) ? targetID : document.getElementById(targetID);
			
			//Ensure target element is found in document before continuing
			if(!targetNode){ return false; }

		} else {

			targetNode = document.body; 
			setCssForFullWindowPdf();
			width = "100%";
			height = "100%";

		}

		if (iframe) {
			targetNode.innerHTML = '<iframe src="' +url + '" class="b-plist-preview_with_pdf"></iframe>';
			return targetNode.getElementsByTagName("iframe");
		} else {
			targetNode.innerHTML = '<object	data="' +url +'" type="application/pdf" width="' +width +'" height="' +height +'"></object>';
			return targetNode.getElementsByTagName("object")[0];
		}
	};

[please not class in iframe - sorry]

then IE11 allows you to embed the PDF.

Thanks for this.

C

**Comment by pipwerks** [comment]
Thanks for this. I'm super busy right now but will take a closer look when I have some time.

**Comment by shinrox** [comment]
+1

**Comment by redasys** [comment]
I added this function to pdfobject.js 
supportsActiveX = function() {
        return (Object.getOwnPropertyDescriptor && Object.getOwnPropertyDescriptor(window, "ActiveXObject")) || ("ActiveXObject" in window);
    };

and then just modify pluginFound() to: if (hasReader() || hasReaderActiveX() || supportsActiveX())

**Comment by pauldenato** [comment]
I added this update to the hasReaderActiveX() and it did the trick for me.

Add this just before the return false at the end of the function.

//added for ie 11 support
if(!document.all) {return true;}

**Comment by pipwerks** [comment]
Thanks for the suggestions. I've written a 2.0 update that I hope to release by the end of the month. It supports IE. I just need to do more testing and write some documentation.
