### ISSUE TITLE
Handling of urlencoded URLs

### ISSUE THREAD

**Issue by Stefaminator** [pipwerks/PDFObject#56]
I am wondering about the following issue. I have a correct encoded URL and I try to send it to the PDFObject like this: 

<code>
var mypdf = new PDFObject({ url: "http://www.example.com?aParam%5B0%5D=1&aParam%5B1%5D=4&aParam%5Ba%5D=b&aParam%5Bc%5D=d" }).embed("pdf");
</code>

I used the php-function http_build_query()  to handle all the necessary escaping  (%5B => [ and %5D => ]), so this string should be equal to <code>aParam[0]=1&aParam[1]=4&aParam[a]=b&aParam[c]=d</code>

If i paste the urlencoded URL in my browser i am able to see the correct PDF.
If i use this URL in PDFObject it seems to be the case that the parameters could not be received from the server. I got it working by using <code><?php urldecode($query_string); ?></code> on my query string before but i do not think this is the correct way.

Don't you think that PDFObject should be able to handle urlencoded URLs? Or is PDFObject encoding the URL by itself so that it was a double encoding issue? Please tell me you opinion.

**Comment by pipwerks** [comment]
Hello

By default, PDFObject encodes the URL querystring values as well as the base URL
https://github.com/pipwerks/PDFObject/blob/master/pdfobject.js#L159
https://github.com/pipwerks/PDFObject/blob/master/pdfobject.js#L235

Currently there is no option to disable this encoding.
