### ISSUE TITLE
What about on load fail?

### ISSUE THREAD

**Issue by jeesus** [pipwerks/PDFObject#57]
My code is following:
`	var pdf = new PDFObject({
	  url: "/pdf/pdf?id=3",
	  id: "newPDF",
	  width: "100%",
	  pdfOpenParams: {
		navpanes: 1,
		statusbar: 0,
		view: "FitH",
	  }
	}).embed("pdfContent");
	$(pdf).load(function() {
		$('#loading').hide();
	});
`

How could I assign a handler to let user know of failure? Right now if for some reason the PDF loading should fail, I only get notices in Console.

**Comment by pipwerks** [comment]
All this library does it write an `<object>` to the page, it does not detect whether the PDF successfully loads or 404s. Unfortunately, detecting whether the file actually loads is very complicated and not easily handled via client-side JavaScript.
