### ISSUE TITLE
Adding a scroll event on the Pdf object

### ISSUE THREAD

**Issue by mjunaidsalaat** [pipwerks/PDFObject#58]
I am trying to add a scroll event to the PDF object I've created with PDFObject. I want user to scroll at least once before submitting the form.

I've tried javascript onscroll and jQuery .scroll() but its no use.

`$('#pdfRenderer')[0].scrollTop` alway return 0 in any position niether the event is working.

Is there a way to achieve this using PDFObject.

Thanks.

**Comment by pipwerks** [comment]
Unfortunately this is not possible. The PDF is usually not a DOM element, it's rendered by PDF reader software. Every browser has its own mechanism for rendering PDFs, there is no standard. In some cases, the PDF might be rendered by PDF.js; in those situations you might be able to detect scrolling. But Adobe Reader, FoxIt, and some of the native PDF rendering don't provide that option.
