### ISSUE TITLE
ActiveX detection for newer IE+/Edge browsers

### ISSUE THREAD

**Issue by RichardLee1001** [pipwerks/PDFObject#59]
Since you are releasing version 2.0 shortly you might have already checked for this however I thought I would mention it anyway.

When detecting if the browser supports ActiveX the existing does not work for all browsers anymore:

`if (window.ActiveXObject)`

I have updated and testing in IE11 to the following which provides a better check:

`if (window.ActiveXObject || "ActiveXObject" in window || window.ActiveXObject !== undefined)`

Please evaluate and include in newer version of component.

Thanks

**Comment by pipwerks** [comment]
Yup, PDFObject 2 uses a similar check. Thanks for the tip!
