### ISSUE TITLE
Release on npm

### ISSUE THREAD

**Issue by huan086** [pipwerks/PDFObject#61]
Time to have a package.json given the new version! =)

**Comment by RichardLee1001** [comment]
Awesome!

**Comment by pipwerks** [comment]
it's on my list. :)

**Comment by pipwerks** [comment]
package.json created and pdfobject registered on npm as 'pdfobject'

I'm a n00b with npm on front-end (I've only used npm with Node/Express on server), please let me know if you run into any issues with the npm packaging. I didn't add `module.exports` to the JS file, not sure how that impacts npm. Thanks!

**Comment by huan086** [comment]
Take a look at https://github.com/moment/moment/blob/develop/moment.js

I see that the code is wrapped in
```
;(function (global, factory) {
    typeof exports === 'object' && typeof module !== 'undefined' ? module.exports = factory() :
    typeof define === 'function' && define.amd ? define(factory) :
    global.moment = factory()
}(this, function () {

... moment.js code ...

    return _moment;

}));
```

The file will thus work when including in `<script>` due to `global.moment = factory()`, and it will work in `require()` due to `module.exports = factory()`

**Comment by pipwerks** [comment]
Interesting, and more convoluted than I expected. Thanks for sharing

**Comment by pipwerks** [comment]
"UMD" is what I was looking for.

https://github.com/umdjs/umd/blob/master/templates/returnExports.js
http://garrettn.github.io/blog/2014/02/19/write-modular-javascript-that-works-anywhere-with-umd/
http://davidbcalhoun.com/2014/what-is-amd-commonjs-and-umd/

**Comment by pipwerks** [comment]
Resolved by https://github.com/pipwerks/PDFObject/commit/a3eeea2dd5d0c59cc552a18b1a602d75730af10c
