### ISSUE TITLE
Use encodeURIComponent

### ISSUE THREAD

**Issue by huan086** [pipwerks/PDFObject#62]
encodeURI isn't the correct function to encode query string parameters. Use encodeURIComponent instead. Also, in `for (prop in pdfParams)`, `prop` should be encoded too

https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/encodeURI

**Comment by huan086** [comment]
I changed my copy to the following. Have not tested it yet

```
            for (prop in pdfParams) {
                if (pdfParams.hasOwnProperty(prop)) {
                    string += encodeURIComponent(prop) + "=";
                    string += encodeURIComponent(pdfParams[prop]);
                    string += "&";
                }
            }

```

**Comment by pipwerks** [comment]
I had a reason for using `encodeURI` over `encodeURIComponent`, but for the life of me I can't remember what it was.

**Comment by pipwerks** [comment]
Oh yes, now I remember. I use `encodeURI` on the passed URL in the `embed` method. `encodeURIComponent` would fail there. But `encodeURIComponent` works well in the spots you suggest

**Comment by pipwerks** [comment]
Updated
