### ISSUE TITLE
How to detect the pdf file has been loaded?

### ISSUE THREAD

**Issue by jiji262** [pipwerks/PDFObject#64]
How to detect the pdf file has been loaded?

**Comment by pipwerks** [comment]
There's no way to know if the PDF has actually loaded.

When you embed a PDF using PDFObject, the `embed()` function returns `false` if PDF embedding is not supported in the browser. If PDF embedding *is* supported, the `embed()` function will return the embedded element (`<embed>` in most cases or `<iframe>` for PDF.js). This is covered on http://pdfobject.com
