### ISSUE TITLE
PDF's from AWS bucket not sized correctly.

### ISSUE THREAD

**Issue by tcclevela** [pipwerks/PDFObject#65]
I'm trying to embed a PDF from a remote source (just using a link to it). When I call PDFObject.embed, it does embed the pdf, but the sizing of the document is completely ignored, and it is rendered as if the entire document were in view (zoomed to the top left corner). Using pdfopenparams has no effect as far as I can tell.

Alternately, when I try downloading the file and using the local resource path, it works fine.

I would appreciate some advice on this, as the project has a deadline coming up soon.

**Comment by pipwerks** [comment]
I'm not sure I understand. Try using static markup and see if you get the same result. You can copy examples from http://pdfobject.com/static.html
