### ISSUE TITLE
Bower package

### ISSUE THREAD

**Issue by yaceq** [pipwerks/PDFObject#66]
Can you create bower package with new version of your library? I can only find 1.2 (https://libraries.io/bower/pdfobject).

**Comment by pipwerks** [comment]
I will look into it, stay tuned.

**Comment by yaceq** [comment]
Anything new in this topic? ;)
Sorry for being so insistent, but we'd like to use your library in our project and bower package would be very, very useful for us.

**Comment by cwbell1** [comment]
A work around is to do an bower install from the repository
``
bower install --save https://github.com/pipwerks/PDFObject.git
``
It will appear in your dependencies as:
   ` "PDFObject": "https://github.com/pipwerks/PDFObject.git"`

**Comment by pipwerks** [comment]
bower info pdfobject2
(named pdfobject2 since pdfobject was already in use and since 2.x contains breaking changes)
