### ISSUE TITLE
Pdf.js (forced) not working in Microsoft Edge

### ISSUE THREAD

**Issue by Thuemj** [pipwerks/PDFObject#67]
Your sample http://pdfobject.com/examples/pdfjs-forced.html is not working in Microsoft Edge. The pdf.js viewer is shown, but no pdf, and a message is displayed (Function expected, viewer.js line 7168) 

The sample https://mozilla.github.io/pdf.js/web/viewer.html from pdf.js is working fine in Microsoft Edge.

**Comment by pipwerks** [comment]
Thanks for reporting the issue. Unfortunately, I'm unable to replicate, it works fine for me. (Famous last words)

![win10edge-pdfjs](https://cloud.githubusercontent.com/assets/300566/14698603/437ec882-0745-11e6-81f6-f9e9a665af3d.png)

For PDF.js handling, PDFObject only writes an iframe to the page; unless the URL for the iframe is incorrect, all other issues are likely to be with PDF.js, not PDFObject.

Do you have any other details you can share?

**Comment by Thuemj** [comment]
Hi Philip

Thank you for your reply.

I have some more details. I have attached a screenshot of the page as it looks on my PC with a bit more information from the developer tools.

[cid:image003.png@01D19BA9.1E7AAEF0]

And here is the part of the script, that throws the error:

[cid:image004.png@01D19BA9.1E7AAEF0]

I have tried on another PC with the same result.

I am using Edge v. 20.10240.16384.0

If you need any other information, just send me a mail.


Best regards,


Thue Møller Jensen

Senior Consultant
IT & Communications
Mobile +45 72 20 25 67
tje@teknologisk.dk

<mailto:tje@teknologisk.dk>Danish Technological Institute
Gregersensvej
2630 Taastrup
Denmark
Telephone +45 72 20 20 00
http://www.dti.dk<http://www.dti.dk/>

Fra: Philip Hutchison [mailto:notifications@github.com]
Sendt: 21. april 2016 07:17
Til: pipwerks/PDFObject <PDFObject@noreply.github.com>
Cc: Thue Møller Jensen <tje@teknologisk.dk>; Author <author@noreply.github.com>
Emne: Re: [pipwerks/PDFObject] Pdf.js (forced) not working in Microsoft Edge (#67)


Thanks for reporting the issue. Unfortunately, I'm unable to replicate, it works fine for me. (Famous last words)

[win10edge-pdfjs]<https://cloud.githubusercontent.com/assets/300566/14698603/437ec882-0745-11e6-81f6-f9e9a665af3d.png>

For PDF.js handling, PDFObject only writes an iframe to the page; unless the URL for the iframe is incorrect, all other issues are likely to be with PDF.js, not PDFObject.

Do you have any other details you can share?

**Comment by Thuemj** [comment]
Hi Philip

I bit more about the problem. It is like you mentioned a bug in pdf.js that was fixed in v 1.4.16.

If I change to pdf.js 1.4.20 (beta), the problem is solved. I guess, that the reason that it is working on your side, is that you have a cached version of a newer version of pdf.js instead of the latest stable version 1.3.91 that your sample is using.

https://github.com/mozilla/pdf.js/pull/6928/files
https://github.com/mozilla/pdf.js/issues/6927

[cid:image003.jpg@01D19BB5.2074B3C0]




Best regards,


Thue Møller Jensen

Senior Consultant
IT & Communications
Mobile +45 72 20 25 67
tje@teknologisk.dk

<mailto:tje@teknologisk.dk>Danish Technological Institute
Gregersensvej
2630 Taastrup
Denmark
Telephone +45 72 20 20 00
http://www.dti.dk<http://www.dti.dk/>

Fra: Philip Hutchison [mailto:notifications@github.com]
Sendt: 21. april 2016 07:17
Til: pipwerks/PDFObject <PDFObject@noreply.github.com>
Cc: Thue Møller Jensen <tje@teknologisk.dk>; Author <author@noreply.github.com>
Emne: Re: [pipwerks/PDFObject] Pdf.js (forced) not working in Microsoft Edge (#67)


Thanks for reporting the issue. Unfortunately, I'm unable to replicate, it works fine for me. (Famous last words)

[win10edge-pdfjs]<https://cloud.githubusercontent.com/assets/300566/14698603/437ec882-0745-11e6-81f6-f9e9a665af3d.png>

For PDF.js handling, PDFObject only writes an iframe to the page; unless the URL for the iframe is incorrect, all other issues are likely to be with PDF.js, not PDFObject.

Do you have any other details you can share?

**Comment by pipwerks** [comment]
Thanks for the update. I will try and update the PDF.js files in my example.
