### ISSUE TITLE
Any possibility to add a custom title/remove title for a PDF?

### ISSUE THREAD

**Issue by silentHoo** [pipwerks/PDFObject#68]
It's a bit off-topic I know, but: it would be nice if we could set a title for a PDF. I've cryptic URLs and want to hide or set a custom title for my PDFs. As I couldn't find any solution in the wild web, do you know if this is possible?

**Comment by pipwerks** [comment]
Can you provide more context? I'm not sure what you mean. Got an example?

**Comment by silentHoo** [comment]
Sorry, my fault: If you embed a pdf into a page on chrome I see a title in the upper toolbar on the left side. Here it's "download", because chrome grabs the information from the url which in my case is `/downloads?id=...`:
<img width="1103" alt="bildschirmfoto 2016-04-27 um 09 13 30" src="https://cloud.githubusercontent.com/assets/1610894/14844561/7dbd13ce-0c58-11e6-9ac9-eddbb6a7b591.png">

Do you know if the browser allows to set a custom title there?

**Comment by pipwerks** [comment]
Sorry, as far as I know, the title can't be changed from the client side. However you can change it from your server, if you have control of the headers (specifically the content disposition header). Here is a decent StackOverflow discussion on the topic: http://stackoverflow.com/questions/14818732/pdf-handler-content-disposition-filename

Good luck

**Comment by yiweicao** [comment]
I have this issue in Chrome and have been using content-disposition. However, it does not help me show another title than an empty bookmark "<placename>".

**Comment by CodeHeight** [comment]
I would like no title.  

![image](https://user-images.githubusercontent.com/20741770/26992315-b59e2a1e-4d23-11e7-93a2-45812640a5d3.png)


I attempted server side code, but no luck.

![image](https://user-images.githubusercontent.com/20741770/26992347-db66cdaa-4d23-11e7-9136-52ca77028662.png)

**Comment by jcyktor** [comment]
@silentHoo Found that Chrome is displaying the PDF DocumentTitle property to display the title for embedded PDFs. The change we made is on our PDF generation side to add a DocumentTitle property. It was not respecting the Content-Disposition header value. @CodeHeight I'm not sure if this will work to give an empty title though. We didn't have that need.
