### ISSUE TITLE
latest js is not compatible with mobile browsers

### ISSUE THREAD

**Issue by jaypatel711** [pipwerks/PDFObject#70]
Hello,

First of all thank you very much for creating wonderful plugin, but It seems plugin is not working on mobile browsers. I have checked on Andriod Chrome and iOS Safari browsers.

Can you please include this support in next version?

**Comment by pipwerks** [comment]
Read the docs. It works as expected on iOS -- iOS Safari does not support
inline PDFs.

**Comment by pipwerks** [comment]
Also note I do not own an Android device, so I can't test there. But I expect it will be similar to iOS, which does not support inline PDFs.

As the docs state, PDFObject is not a rendering engine for PDFs -- it just writes embed code, which tells the browser to use its own PDF rendering engine to display the PDF. If the browser doesn't support inline PDFs, there's nothing PDFObject can do about it. You can choose to implement your own copy of PDF.js if you absolutely need mobile support. Check the docs and examples for the PDF.js options. http://pdfobject.com
