### ISSUE TITLE
Question: Can I render custom buttons to the PDF viewer?

### ISSUE THREAD

**Issue by lukeed** [pipwerks/PDFObject#71]
Or is that completely controlled by the browser's native behavior?

**Comment by pipwerks** [comment]
The buttons are part of the PDF rendering engine, provided by the browser or plugins like Adobe Reader. Not something that can be modified consistently across platforms.

You *might* be able to create custom buttons in PDF.js and force the PDF to render via PDF.js. But PDF.js is a different utility, unrelated to PDFObject, so I can provide any guidance there, aside from my documentation on how to force the browser to use PDF.js (see http://pdfobject.com)

Good luck

**Comment by lukeed** [comment]
Yeah. You can with PDF.js, but I've been waiting on this 2.0 to see if, perhaps, you'd introduce an injection point into the renderer.... because I don't need ALL of the behemoth that is PDF.js

**Comment by pipwerks** [comment]
I wish it were possible, but there is no standard API (and sometimes no API at all) for PDF rendering apps. Look at Google Chrome's built-in PDF renderer: it's been around for 5+ years and still doesn't support some of the basic PDF Open Parameters established by Adobe 10 years ago, despite huge discussion threads from developers practically begging Google to implement the feature(s). 

(There's no requirement for Google to follow Adobe's lead, but Adobe had a pretty firm hold on PDF rendering marketshare for a decade and was a defacto standard, so it seems like a good starting point.)

PDF.js is changing the game, but as you mention, comes with quite a bit of weight.
