### ISSUE TITLE
Does IE9-11 support?

### ISSUE THREAD

**Issue by nickylee864** [pipwerks/PDFObject#72]
IE 11 shows that this browser does not support inline PDFs. Please download the PDF to view it: Download PDF.Do I need some special settings?

**Comment by pipwerks** [comment]
You need to install a PDF rendering plugin such as Adobe Reader or FoxIt. 

PDFObject does not render PDFs -- it just places embed code in the HTML. If the browser doesn't support PDFs, you will see the message you pasted above. IE9-11 do not natively support PDFs, you need to install a 3rd party plugin such as Adobe Reader, or use the PDF.js alternative (which is a separate JS utility and not part of PDFObject).

**Comment by nickylee864** [comment]
Thank you very much!!!  Could you improve it when people use ie browser then given them a tip to install a Adobe Reader or something else. I'm so sorry about that my English is poor , I don't know if you know exactly what I mean. Thank you again!

**Comment by pipwerks** [comment]
This is already possible -- you can customize the fallback text. See "fallbackLink" under https://pdfobject.com/#api
