### ISSUE TITLE
record the reading progress

### ISSUE THREAD

**Issue by ennalalala** [pipwerks/PDFObject#73]
I want to record the reading progress when I use PDFObject. who can put an example? or other, when you import a pdf and turn the page, how to extract the current page? thanks.

**Comment by pipwerks** [comment]
Unfortunately, this is not a feature supported by PDFObject, because it's not currently possible in most PDF rendering applications. You may be able to do it if you force all users to load the PDF via PDF.js, but PDF.js is a different utility and outside the scope of PDFObject.
