### ISSUE TITLE
HELP: Can't manage to make PDF.js fallback work

### ISSUE THREAD

**Issue by keabard** [pipwerks/PDFObject#74]
Hi,

not really an issue, just a total misunderstanding of how I can use PDFObject with the PDF.js fallback option. I'm on a project managed by webpack.

I tried many things to make this work, including trying to build PDF.js sources myself, using pdfjs-dist package on npm, all of that with different webpack imports and different PDFObject parameters. Final result, i'm pretty lost about what I should do, so I'll just explain the problem I just encountered from a clean slate.

In order to make PDF.js fallback work with PDFObject, I understand that my project has to deliver a PDF.js viewer HTML file. This file is nowhere to be found in pdfjs-dist package. How should I proceed ?

- Should I make my own viewer.html ? Hence, are there any existing HTML files that could give me inspiration ?

OR

 - Should I directly import pdf.js package in my project and build it with their `gulp dist` method in order to make it build a viewer.html that I'll be able to use ? If so, how should I do it ?

Thank you

**Comment by huan086** [comment]
Download directly from https://mozilla.github.io/pdf.js/getting_started/
The pdfjs-dist package contains the core rendering logic, but no viewer

**Comment by pipwerks** [comment]
Echoing huan086, go to the Mozilla link and check out the section "Trying the Viewer". That's all I did for my examples, it was up and running in just a few minutes. Note the PDF must be on the same domain as the HTML file.

**Comment by keabard** [comment]
Thanks a lot !
