### ISSUE TITLE
How prevent pdf from downloading automatically(IDM)?

### ISSUE THREAD

**Issue by alireza1375** [pipwerks/PDFObject#75]
When any pdf files are opened in browser, it start to downloading.it is not opened in browser.
Is there a way to disable the automatic download in IDM.

**Comment by pipwerks** [comment]
This is beyond the scope of PDFObject. 

If the server sets the content disposition to 'attachment', the user will be prompted to save the file. This cannot be changed on the client side.

**Comment by irfanaslam-me** [comment]
you can do this remove the pdf file type from IDM it will not start automatically [Screen Shot](https://imgur.com/DZbWyUq.png)
