### ISSUE TITLE
open in a new tab?

### ISSUE THREAD

**Issue by raysefo** [pipwerks/PDFObject#78]
Hello,

I wonder if I display documents (pdf, jpg etc.) on a new tab when user click on a link?

Best Regards.

**Comment by pipwerks** [comment]
Browsers that have native PDF support will display the PDF in the new tab, if the URL points directly to the PDF. Same for images. No need for HTML unless you want to control the layout. PDFObject is designed to embed PDFs in HTML pages, so your scenario is outside of the scope of PDFObject.
