### ISSUE TITLE
pdfOpenParams with base64 url not working

### ISSUE THREAD

**Issue by prabhakerb** [pipwerks/PDFObject#80]
I am passing base64string as url with pdfOpenParams but did not work for me. Could you please suggest?. I would like to turn off toolbar etc..

example:
pdfurl="data:application/pdf;base64,JVBERi0xLjQKJeLjz9MKCjEgMCBvYmoKPDwvVHlwZSAvQ2F0YWxvZwovUGFnZXMgMiAwIFI+PgplbmRvYmoKCjIgMCBvYmoKPDwvVHlwZSAvUGFnZXMKL0tpZHMgWzMgMCBSXQovQ291bnQgMT4+CmVuZG9iagoKNiAwIG9iago8PC9MZW5ndGggNyAwIFIKL0ZpbHRl.....";
PDFObject.embed(pdfurl, "#pdf_object", options);

**Comment by pipwerks** [comment]
Can you try it with static markup to see if it works there?

You can use the generator to create the markup for you: https://pdfobject.com/generator

**Comment by devthiagolino** [comment]
How do I change the title "Sample" for something else?

**Comment by pipwerks** [comment]
Closing from lack of response.
