### ISSUE TITLE
browser compatibility

### ISSUE THREAD

**Issue by Shysoong** [pipwerks/PDFObject#81]
i used PDFObject in ie11,but not supported

**Comment by pipwerks** [comment]
PDFObject is supported in IE11.

PDFObject relies on the browser's native support for PDF rendering. If the browser doesn't support PDF rendering, no PDF is displayed. IE11 doesn't have a native PDF viewer, so PDFs will not appear unless a plugin or PDF.js are used. This is not a bug in PDFObject.
