### ISSUE TITLE
Not Shown PDF only show white screen but after download pdf is those i rendered 

### ISSUE THREAD

**Issue by VishalViradiya** [pipwerks/PDFObject#83]
![testre](https://cloud.githubusercontent.com/assets/14134346/15651933/58a27e96-26a0-11e6-8fe6-9a616c7b89f2.png)
 as you see pdf not display

**Comment by huan086** [comment]
Make sure that the GetBOMFile sets the mime type as application/pdf

**Comment by pipwerks** [comment]
Try it with hard-coded HTML (not JavaScript) and see if it makes a difference. Use the generator to create your HTML. [http://pdfobject.com/generator](http://pdfobject.com/generator)

**Comment by VishalViradiya** [comment]
Hi
Issue is solved by  i have return from my  mvc Controller is BytesArray but need  to return  Stream 
And thank you for your suggestion.
