### ISSUE TITLE
PDFObject can't support IE9

### ISSUE THREAD

**Issue by yizhigui** [pipwerks/PDFObject#86]
![image](https://cloud.githubusercontent.com/assets/7477252/16295477/b905a92c-3959-11e6-98e3-2573993999ea.png)

help! help! help!

**Comment by pipwerks** [comment]
Hello

IE9 is supported. 

If you would like help, you need to provide more details about your situation. For example, is this screenshot from your page or from one of my examples on PDFObject.com? If it's from your page, are you using IE's compatibility mode? If you're configuring IE9 to behave like IE8 via compatibility mode, PDFObject will not function. This is one of many scenarios that could lead to your screenshot.

Thanks

**Comment by ax772090** [comment]
Hello
This is my code.
`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>PDFObject Example</title>
    <script src="js/pdfobject.js"></script>
</head>
<body>
  <script>
       PDFObject.embed("pdf/sample-3pp.pdf");
  </script>
</body>
</html>`

IE9 shows:
![ie](https://cloud.githubusercontent.com/assets/20105608/16354572/a94bf7e4-3aca-11e6-83ed-3bb7d75d3747.png)

**Comment by pipwerks** [comment]
Do you have a PDF rendering plugin installed?? IE9 does not include PDF support by default, you will need to install Adobe Reader or similar plugin.

**As stated in the docs, PDFObject does not change browser support for PDFs, it only writes embed code to the HTML.** If the browser doesn't natively support PDFs -- and IE9 doesn't -- PDFObject will _correctly_ tell you PDFs are not supported. If you add a plugin like Adobe Reader or FoxIt, PDFObject will correctly tell you that PDFs are supported.

**Comment by ax772090** [comment]
Thank you!!  I didn't have a PDF rendering plugin installed! **After the installation is complete, I can use It.**

**Comment by pipwerks** [comment]
Glad you got it working :)
