### ISSUE TITLE
page param don't work in edge browser win10

### ISSUE THREAD

**Issue by a-du** [pipwerks/PDFObject#88]
var options = {
    page: "2"
};
PDFObject.embed("/pdf/sample-3pp.pdf", "#my-container", options);

**Comment by a-du** [comment]
how can i get current page of pdf file?

**Comment by pipwerks** [comment]
Not all PDF rendering engines support the page parameter.

Also, there is no standardized way to query page numbers from the PDF rendering system.

Both of these items are outside the scope of PDFObject, which simply embeds PDFs to the HTML file.

**Comment by a-du** [comment]
ok$B!$(Bi see$B!$(Btks

?$B<+2fE*(B iPhone

$B:_(B 2016$BG/(B7$B7n(B30$BF|!$(B02:08$B!$(BPhilip Hutchison <notifications@github.com<mailto:notifications@github.com>> $B<LF;!'(B


Not all PDF rendering engines support the page parameter.

Also, there is no standardized way to query page numbers from the PDF rendering system.

Both of these items are outside the scope of PDFObject, which simply embeds PDFs to the HTML file.

-
