### ISSUE TITLE
Supporting MVC and Knockout

### ISSUE THREAD

**Issue by SwartHack** [pipwerks/PDFObject#90]
Hey Phil!
PDFObject has saved me a ton of work. Great Job!
I am using ASP.NET/MVC5. I am also using knockout. 
It is working as advertized, mostly

1. One thing that got me digging into the guts was a small issue with how it parses out a filename from "src". With MVC routing there is never a sure way to effectively do this, unless you want to start trying to parse the entire URL, looking for a possible candidates, wouldn't be my choice. If we could provide an argument to embed for a display name, like what I call FileFriendlyName in my knockout view model, it would be great. Currently, my filename in the toolbar is always "fileview", that's because the URL is localhost:/fileview?filename. And sometimes its localhost:/fileview?filename&xhr=true, for ajax/json requests.

2. Speaking of ajax/json, When I load the first file:

```
 var pdfembed = document.getElementById('pdf-embedded');

            if (pdfembed == null) {
                pdfobj = PDFObject.embed(fileviewUrl, $('.mainDocumentContainer .inner-document'), { id: "pdf-embedded" });
                while(!pdfobj) {}
                pdfembed = document.getElementById('pdf-embedded');
            }
            else
            {
                $(pdfembed).attr('src',fileviewUrl);
            }
.
.
```
I know the empty while{} is not a good idea, was just testing, and I couldn't get a 'load' eventlistener ever to fire. will eventually eliminate...

So heremaybe you can possible see the problem with embed in an async implementation. The first embed works great, but if I try to just update the .pdf-objectcontainer's src, it doesn't change.

If I just re-run:
`pdfobj = PDFObject.embed(fileviewUrl, $('.mainDocumentContainer .inner-document'), { id: "pdf-embedded" });`

It works, but it appends .pdfobject-container to the existing targer, everytime. So after awhile I believe you would hit a limit of max tags or something, plus it must not make the DOM very happy.

`<div class="inner-document pdfobject-container pdfobject-container .......">`

So really the easy fix here is address the classname duplicate problem, but I am unaware of what other problems with-in the content it may be causing?

3. On the content issue, I was trying to grab the container content and just update the 'span#title' with my friendly filename , but it is always empty, or I am doing it wrong.
```
var pdfobj = document.getElementById('pdf-embedded').contentDocument;
            if (pdfobj)
            {
                var ele = pdfobj.getElementsByTagName('span#title');
            }
```
I can inspect it in debug obviously.

4. Not an issue, but my request. To provide the ability to us a bound knockout variable for the .pdf-objectcontainer. Then all kinds of cool element caching/binding is taken care of for you automagically.

Here is my a snippet from my model.js:
`var viewmodel = {

        // thumbnails
        // list of files

        thumbnails: ko.observableArray(),

        // main file
        //-------------------------

        mainfileurl: ko.observableArray(''),
        filepubliclink: ko.observable(''),
        exif: ko.observableArray(),
        name: ko.observableArray(),
        friendlyname: ko.observable(''),
        filedescr: ko.observable(''),

        // comments
        //-------------------------

        comment: ko.observableArray(),
        addComment: function (item) {
            this.comments.unshift(item);
        },
        removeComment: function (item) {
            this.comments.remove(item);
        },
.
.
.}`

Here is how I currently use it for my image gallery:
`<img class="main-image well-sm" data-bind="attr: { src : mainfileurl,  alt: friendlyname }" />`

So when I click a thumbnail,  it uses ajax to get  the metadata, then on the callback all I do is set knockout vars values ko does the rest. If its a cached element it loads it, otherwise calls server for file.

```
deferred.done(function (data) {
            if (!data || !data.Url) {
                console.error('invalid data from server', data);
                return;
            }

            if (!fileUrl) {
                viewModel.mainfileurl(data.Url);
            }

            viewModel.filepubliclink(data.FileMainPage);
            viewModel.comments(data.Comments);

            // more EXIF stuff!!!!!!!!!!!
            var exif = parseEXIF(data.EXIF);
            if (!exif)
            {
                viewModel.exif(exif);
                exif.length ? $('.image-info.image-exif').fadeIn() : $('.image-info.image-exif').fadeOut();
            }
           

            viewModel.name(data.Name);
            viewModel.friendlyname(data.FileFriendlyName);
            viewModel.filedescr(data.FileDescr);

            data.FileDescr ? $('.image-info-descr').fadeIn() : $('.image-info-descr').fadeOut();

            $('#ImageVPath').val(data.FileVPath);
            $('#ImageVPathEditImageInfo').val(data.FileVPath);

            viewModel.friendlyname(data.FileFriendlyName);
            controller.show('main-image');
.
.
`

Here is how I create my thumbnails:
`<script id='thumbnailsTemplate' type="text/x-jquery-tmpl">
    <li>
        <a href="${Url}" data-vpath="${VPath}" data-mime-type="${MimeType}">
            <img class="thumbnail" src="${UrlThumbnail}" />
            <div class="caption text-center">
                <h6>"${FileFriendlyName}"</h6>
            </div>
        </a>
    </li>
</script>`

So, what would be cool is:
`<div class="inner-document pdfobject-container">
<embed id="pdf-embedded" data-bind="attr: { src : mainfileurl,  alt: friendlyname }" class="pdfobject" type="application/pdf" style="overflow: auto; width: 100%; height: 100%;" internalinstanceid="6" title=""></div>`


Phew, there ya go. I hope it all falls together for you as far as making sense. Let me know what you think. I could try to contribute, but wouldn't want to jump in cold. Thanks again for this great lib.

Eric

**Comment by SwartHack** [comment]
not sure why it re-numbered the items?!!!

**Comment by pipwerks** [comment]
Hi SwartHack

Sorry for the delayed response, life got in the way. Umm... this is a really long post and hits multiple topics. Since this is the repo's 'issues' section, each question/topic should have its own entry for cleaner handling. I will close this thread as being too broad (sorry). If you're still chasing down the issues you mentioned, please file each separately.

BTW, the duplicate classnames issue is a good catch, thanks.

**Comment by SwartHack** [comment]
Hey Phil,
No worries. I understand the nature of these projects.
Yeah, sorry about the ramble. I haven’t “contributed” before and usually avoid forums!-)
Typically, I have moved past this, for now, but did mean to get back to my posted issues.
Thanks for cleaning that up for me.

A few quick hits for you.

This is the fix I came up with for multiple class names:

!(targetNode.classList.contains("pdfobject-container")) && targetNode.classList.add("pdfobject-container");
//targetNode.className += " pdfobject-container";


I have also made some changes to options to allow knockout binding params and a display friendly name.
But it seems both working are an issue of <embed> known problems with knockout.
In order for knockout to work you have to remove and re-add the data-bound element.
Which basically is what running embed does each time, so no big diff, except maybe for large pdf?
I will be revisiting this shortly. Will update the proj with any info/solutions.

Thanks for this nice piece of work. I was looking at extending it to deal with any HTML5 <embed> or <object>.
You’d have to rename it though ☺

Cheers

Eric
