### ISSUE TITLE
Bower Pulls Old Version

### ISSUE THREAD

**Issue by thejwalker** [pipwerks/PDFObject#91]
Love PDFObject.  Just wanted to give you a heads up that doing 

> bower install pdfobject

Installs the old version 1.2.0.  Gave me a few minutes of hair pulling until I figured it out.

Thanks

**Comment by CExpertLatam** [comment]
+ 1 in this issue

**Comment by GuidoKoepke** [comment]
Installs the old version 1.2.0. ...What is the Solution for that issue?

**Comment by pipwerks** [comment]
Thanks for the heads' up. I don't personally use Bower, so I hadn't noticed. The bower.json file appears correct, so I'm not sure what's going on, I'll look into it when I get a chance. Please share if you have any suggestions/leads. Thx

**Comment by miqid** [comment]
I've just stumbled across this problem as well.

It seems like somebody took the liberty of registering this source repository with Bower under the name `pdfobject2`, so you can try `bower install pdfobject2` instead.

@pipwerks, if you want your repository to be associated with `pdfobject` when installing via Bower, I suspect you'll need to ask @rkmax (owner of the other fork) to `unregister` their repository.

**Comment by pipwerks** [comment]
Thanks for the reminder... I forgot that PDFObject had already been taken in Bower, so I registered under PDFObject2, as you discovered.
