### ISSUE TITLE
restrict pdf tool

### ISSUE THREAD

**Issue by vinoth3690** [pipwerks/PDFObject#92]
how to do workout  donot want show download print and save option

**Comment by pipwerks** [comment]
Toolbar controls are at the mercy of the browser of PDF rendering software. PDFObject does not provide any extra control aside from what is provided by the browser or PDF plugin (such as Adobe Reader). If you want to fine-tune control of the toolbars, you can try forcing the browser to use PDF.js to render the PDF, then modify your toolbars via PDF.js. This is outside the scope of PDFObject.

**Comment by pipwerks** [comment]
Duplicate of https://github.com/pipwerks/PDFObject/issues/85
