### ISSUE TITLE
Firebox browser support all toolbars other browser not showing toolbars

### ISSUE THREAD

**Issue by vinoth3690** [pipwerks/PDFObject#94]
[http://stage.reasolutions.in/pdf/](url)

http://stage.reasolutions.in/pdf/

I donot want to show pdf toolbar

**Comment by pipwerks** [comment]
PDF toolbar visibility is controlled by the browser and/or PDF rendering plugin (eg Adobe Reader). PDFObject cannot control the visibility of the toolbar.

Duplicate of https://github.com/pipwerks/PDFObject/issues/85
