### ISSUE TITLE
PDF Layers

### ISSUE THREAD

**Issue by ashattack** [pipwerks/PDFObject#98]
I have a pdf will several layers that I would like to be able to turn off and on. However, I can't seem to find information on how to insert the PDF navigation bar into my iframe were my pdf is located. This navigation bar is always included in the desktop version of Adobe Reader. Can you guys help point me in the right direction?

**Comment by pipwerks** [comment]
There is no standardized API for controlling PDF elements, you're at the mercy of the browser vendors and/or plugins. PDFObject only embeds PDFs into the page, it does not provide the level of control you're seeking.
