### ISSUE TITLE
Can't we Hide toolbar of pdf file in firefox ?

### ISSUE THREAD

**Issue by mallikarjuna909** [pipwerks/PDFObject#99]
Basically.. i picked PDFObject mainly for hiding/Removing the toolbar. But even i can see the toolbar, this is particularly for "**Firefox**".

Are you sure is this working in Firefox? If Yes send me solution.

Here is my trial

var options = {
pdfOpenParams: {
view: 'Fit',
scrollbars: '0',
**toolbar: '0',**
statusbar: '0',
navpanes: '0'
}
};
PDFObject.embed('MyPdf.pdf', ".box-content", options);

**Comment by pipwerks** [comment]
This is already covered:

https://github.com/pipwerks/PDFObject/issues/85
https://github.com/pipwerks/PDFObject/issues/94

Also, please read the docs at http://pdfobject.com. Under "What PDFObject doesn't do:"

"PDFObject does not magically implement PDF Open Parameters. As mentioned above, these parameters are not widely support. The PDF rendering engine either supports them or doesn't — PDFObject cannot force the rendering engine to implement these features."

Browsers handle PDF Open Parameters differently (if at all). It is not possible (via PDFObject or JavaScript) to force browsers to support PDF Open Parameters if the browser vendor did not build an API for it.
